In [22]:
import numpy as np
import pandas as pd
post = pd.read_csv('posts.csv')
user = pd.read_csv('users.csv')
view = pd.read_csv('views.csv')

In [23]:
user.head()

                        _id                  name gender      academics
0  5d60098a653a331687083238  Nivesh Singh Chauhan   male  undergraduate
1  5d610ae1653a331687083239         Gaurav Sharma   male       graduate
2  5d618359fc5fcf3bdd9a0910         Akshay Mishra   male  undergraduate
3  5d6d2bb87fa40e1417a49315        Saksham Mathur   male  undergraduate
4  5d7c994d5720533e15c3b1e9         Varun Chowhan   male  undergraduate

In [24]:
post.head()

,_id,title,category,post_type
0,5d62abaa65218653a132c956,hello there,Plant Biotechnology,blog
1,5d6d39567fa40e1417a4931c,Ml and AI,Artificial Intelligence|Machine Learning|Infor...,blog
2,5d7d23315720533e15c3b1ee,What is an Operating System ?,Operating Systems,blog
3,5d7d405e5720533e15c3b1f3,Lord Shiva,Drawings,artwork
4,5d80dfbc6c53455f896e600e,How Competition law evolved?,Competition Laws,blog

In [25]:
view.head()

,user_id,post_id,timestamp
0,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z
1,5ed3748576027d35905ccaab,5ed4cbadbd514d602c1531a6,2020-06-01T09:39:20.021Z
2,5ed0defa76027d35905cc2de,5eac305f10426255a7aa9dd3,2020-06-01T08:12:42.682Z
3,5ed0defa76027d35905cc2de,5ed1ff0276027d35905cc60d,2020-06-01T08:10:23.880Z
4,5ed0defa76027d35905cc2de,5ed3820f76027d35905ccac8,2020-06-01T08:08:54.124Z

In [26]:
user.shape

(118, 4)

In [27]:
post.shape

(493, 4)

In [28]:
view.shape

(1449, 3)

In [29]:
user.describe()

                             _id                  name gender      academics
count                        118                   118    118            118
unique                       118                   118      3              3
top     5d60098a653a331687083238  Nivesh Singh Chauhan   male  undergraduate
freq                           1                     1     72             68

In [30]:
post.describe()

                             _id             title     category  post_type
count                        493               493          465        493
unique                       493               477          231          4
top     5d62abaa65218653a132c956  PENCIL RENDERING  Photography    artwork
freq                           1                 3           81        241

In [31]:
view.describe()

,user_id,post_id,timestamp
count,1449,1449,1449
unique,118,495,1449
top,5d60098a653a331687083238,5ec1fd0974f7660d73aa0fd5,2020-06-01T10:46:45.131Z
freq,230,18,1

In [32]:
user.isna().sum()

_id          0
name         0
gender       0
academics    0
dtype: int64

In [33]:
post.isna().sum()

_id            0
title          0
category      28
 post_type     0
dtype: int64

In [34]:
view.isna().sum()

user_id      0
post_id      0
timestamp    0
dtype: int64

In [35]:
post[post['category'].isna()]

,_id,title,category,post_type
24,5ddeb6e80eb5e25a8a07f065,Library Managment System: Software Requirement...,NaN,project
25,5de179d80eb5e25a8a07f079,Navigation system using BFS DFS algorithms,NaN,project
29,5dee9b5042a8854bf6eabaaf,Computer Aided Machine Drawing (CAMD),NaN,project
65,5e3ea110eab55d319938a7a7,OS,NaN,project
88,5e4c3873f5561b1994c8e3d9,Bill Calculation(PHP),NaN,project
93,5e4da502f5561b1994c8e42c,Prime No.(PHP),NaN,project
94,5e4da7c8f5561b1994c8e439,Factorial of a No.(PHP),NaN,project
95,5e4dab15f5561b1994c8e446,Palindrome No.(PHP),NaN,project
96,5e4ed85af5561b1994c8e470,Factorial (.net),NaN,project
97,5e4ed8ccf5561b1994c8e47d,Leap year checking (.net),NaN,project
98,5e4edd1bf5561b1994c8e48a,Delegates(.net),NaN,project
99,5e4edd87f5561b1994c8e497,Overloading Method(.net),NaN,project
227,5e8c2d01a3258347b42f2627,Even and Odd Numbers (PHP),NaN,project
228,5e8c993da3258347b42f264d,Armstrong No.(C# .Net),NaN,project
229,5e8cb88ea3258347b42f267e,Palindrome (C# .Net),NaN,project
230,5e8cc876a3258347b42f26a3,Negative or Positive No. (PHP),NaN,project
231,5e8ccfb5a3258347b42f26bc,Friend Number (C# .Net),NaN,project
352,5ea5aacd10426255a7aa9b71,Photography Composition,NaN,project
353,5ea5ce9310426255a7aa9b8d,Photography,NaN,project
374,5eaf3d4110426255a7aa9f4c,Students Networking!,NaN,blog
394,5eb1df6d10426255a7aaa029,Novel & Consenent (P.H.P),NaN,project
442,5eca8fceeaff6b0c3a58a3c0,Zero-Waste Lifestyle,NaN,project
463,5ed0e31a76027d35905cc302,Designing Cmos circuit from Boolean expression...,NaN,project
464,5ed0e65976027d35905cc356,Moore FSM Sequence Detector,NaN,project
465,5ed0f0c576027d35905cc3c7,Designing Circular Microstrip Antenna,NaN,project
468,5ed175f176027d35905cc554,GAN's Introduction,NaN,project
469,5ed175f476027d35905cc562,GAN's Introduction,NaN,project
490,5ed3ef4cbd514d602c1530f2,Recommendation Engine,NaN,project

In [36]:
post['category'].unique()

array(['Plant Biotechnology',
       'Artificial Intelligence|Machine Learning|Information Technology',
       'Operating Systems', 'Drawings', 'Competition Laws', 'Eco System',
       'Economic Policies', 'Graphic|Graphic Design', 'Painting',
       'Pen and ink', 'Computer Technology|Information Technology',
       'Drawings|Painting',
       'Graphic Design|Visual Arts|Illustration|Graphic',
       'Drawings|Calligraphy', 'Photography', 'Empowerment', nan,
       'Video editing', 'Inorganic Chemistry', 'Programming languages',
       'Conceptual|Graphic Design', 'HR Management',
       'Human Resources|HR Management',
       'Mass Media|International Relations', 'Sculptures|Artistic design',
       'Fashion Design|Ceramics|Artistic design', 'Craft|Artistic design',
       'Fashion Design|Visual Arts|Conceptual|Artistic design',
       'Photography|Fashion Design|Visual Arts|Graphic Design|Artistic design',
       'Fashion Design|Visual Arts|Graphic Design|Artistic design|Graphic|Illustration',
       'Mathematics|Linear Algebra',
       'Electronics & electrical Technology|Electrical Machines',
       'Auditing|Internal Audit', 'E Commerce|E Transactions',
       'Computer Technology|Computation',
       'Auditing|Internal Financial Control', 'Taxation|Custom Laws',
       'Auditing|Audit Evidence', 'Taxation|GST', 'Taxation|Direct Tax',
       'Auditing|Secratarial Audit', 'Banking|Banking Companies',
       'Banking|Banking Technology', 'Auditing|Audit Remark',
       'Auditing|Cost Audit', 'Auditing|Statuary Audit',
       'Computer Technology|Programming languages',
       'Legal Studies|Legal System', 'Sports Coaching|Sports Law',
       'Economics|Economics Sociology', 'Economics|Revenue Concept',
       'Human Rights|Rights and Duties',
       'Sociology|Sociology of Religion', 'Sociology|Sociology in India',
       'Political Science|International Politics',
       'Political Science|Colonialism In India',
       'Legal Studies|Labor Law',
       'Computer Technology|Design and Analysis of Algorithms|Programming languages',
       'Computer Technology|Computer Application|Programming languages|Information Technology',
       'Graphics|Computer Creation', 'E Commerce|Other Online Platforms',
       'Drawing', 'Drawings|Artistic design',
       'Drawings|Artistic design|Illustration',
       'E Commerce|Shopping Platform|Other Online Platforms',
       'Computer Technology|Hardware|Information Technology',
       'Computer Technology|Computation|Computer Application',
       'Business|Business Skills',
       'Computer Technology|Computer Application|Hardware|Information Technology',
       'Computer Technology|Computer Application',
       'Computer Technology|Mobile Applications',
       'Computer Technology|Computer Application|Operating Systems',
       'Computer Technology|Information Technology|Computer Application',
       'Computer Technology|Computer Application|Information Technology',
       'Communication|Basics of Communiaction',
       'Drawings|Painting|Visual Arts|Graphic Design|Prints|Illustration',
       'Drawings|Visual Arts|Painting|Graphic Design|Artistic design|Illustration',
       'Computer Technology|Artificial Intelligence',
       'Marketing|Advertising', 'Political Science|Political Thought',
       'Accounting|Fundamental Of Accounting', 'Mixed Media',
       'Management|Team Mangememnt',
       'Business|Corporate Social Responsibilities',
       'Philosophy|Applied Ethics',
       'Human Resources|Performance In Organization|Organizational Behaviour|HR Management',
       'Fashion Desigining|Fashion Textile|Fashion Manufacturing|Fashion Techniques|Garment Production|Garment Technology',
       'Marketing|Promotion And Distribution Decisions',
       'Biotechnology|Genetic Engineering', 'Physiology|Neurology',
       'Mass Media|Indian Government', 'Physiology|Osteology',
       'Physiology|Cardiology', 'Zoology|Ecology',
       'Computer Technology|Cloud Computing', 'Physiology|Radiology',
       'Computer Technology|Operating Systems',
       'Biotechnology|Molecular Biology',
       'Physiology|Gastroenterology|Cardiology', 'Philosophy|Logic',
       'Watercolours', 'Drawings|Watercolours', 'Mixed Media|Conceptual',
       'Drawings|Painting|Watercolours', 'Visual Arts', 'Conceptual',
       'Tapestry', 'Calligraphy',
       'Human Resources|Performance In Organization',
       'Computer Technology|Robotics|Data Science|Information Technology|Artificial Intelligence',
       'Philosophy|Public Philosophy', 'Digital Marketing',
       'Mass Media|Videography',
       'Drawings|Painting|Visual Arts|Artistic design|Watercolours|Acrylics',
       'Biotechnology|Plant Biotechnology',
       'Sports Coaching|Sports Event',
       'Political Science|Government and Politics',
       'Geography|Physical Geography', 'Computer Technology|Data Science',
       'Computer Technology|Machine Learning', 'Graphic Design',
       'Graphic Design|Visual Arts', 'Education',
       'Business|Business Organisation', 'Zoology|Environmental Biology',
       'Human Rights|Fundamental Rights',
       'Computer Technology|Design and Analysis of Algorithms',
       'Marketing|Marketing Management',
       'Accounting|Partnership Accounting|Corporate Accounting|Accounting Theory And Practices',
       'Legal Studies|Income Tax Laws',
       'Graphics|Articulation|Computer Creation',
       'Archeology|Human Prehistory',
       'Business|Start Ups|Entreperneurship|Business Strategies|Venture Capitalist|Business Planning',
       'Geography|Indian Geography',
       'E Commerce|Shopping Platform|Other Online Platforms|Digital India',
       'Business|Bio-entrepreneurship', 'Literature|Stories',
       'History|Indian History', 'ViDEO',
       'Management|Business Management', 'Visual Arts|Photography',
       'Social Work|Health Education', 'Social Work|Social Tech',
       'Social Work|Humanities', 'Photography|Visual Arts',
       'Accounting|Financial Accounting', 'Psycholgy|Social Psychology',
       'Photography|Conceptual', 'Physics|Instrumentation', 'Craft work',
       'Social Work|Social Interventions|Substance Abuse',
       'Economics|Indian Economy',
       'Social Work|Substance Abuse|Social Interventions|Humanities',
       'Social Work|Social Interventions|Substance Abuse|Health Education',
       'Social Work|Humanities|Social Interventions',
       'Finance|Financial Analysis', 'Architecture',
       'Photography|Architecture|Painting',
       'Computer Technology|Cloud Computing|Artificial Intelligence|Information Technology|Programming languages',
       'Computer Technology|Design and Analysis of Algorithms|Web designing|Database Management|Artificial Intelligence',
       'Literature|Movements in Literature',
       'Physics|Atomic Physics|Energy Physics|Quantum Mecahnics|Instrumentation',
       'Business|Business Strategies|Venture Capitalist',
       'Photography|Architecture|Illustration',
       'Photography|Architecture',
       'Human Rights|Fundamental Rights|Protection & Enforcement',
       'Environment Studies|Pollution|Environmental Biology',
       'Photography|Conceptual|Illustration',
       'Physics|Quantum Mecahnics|Industrial Instrumentation|Atomic Physics|Nuclear & Particle Physics|Energy Physics',
       'Biotechnology|Environmental Biotechnology',
       'Legal Studies|Alternate Dispute Resolution|International Treaties|International Agreement',
       'Marketing|Principles Of Marketing|Marketing Research Methadology|Marketing Management|International Marketing',
       'Sculptures', 'Psycholgy|Child Development',
       'Economics|Economic Policies|Break even Point|Foreign Economy',
       'Psycholgy|Psychological Growth',
       'Management|Business Management|Technology Mangement|Managerial Activity|Creative And Lateral Management',
       'Business',
       'Business|Business Strategies|Business Enviorment|New Venture Planning|Foreign Business|Business Organisation',
       'Marketing|Principles Of Marketing|International Marketing|Promotion And Distribution Decisions',
       'Social Work|NGO', 'Fine Arts|Painting',
       'Legal Studies|Legal System|Legal Tradition|Nationality Law|Government Law',
       'Business|Entreperneurship|Venture Capitalist|Business Enviorment|Start Ups|Business Planning|New Venture Planning',
       'Legal Studies|Company Law|Legal System|Banking Law',
       'Computer Technology|Web designing|Artificial Intelligence|Computer Application|Machine Learning|Frontend Development',
       'Music', 'Sculptures|Wood Crafts|Craft|Wood carving',
       'Fashion Design', 'Painting|Craft|Artistic design',
       '2D Composition|Watercolours|Painting',
       'Painting|Watercolours|2D Composition',
       'Visual Arts|Craft|Conceptual',
       'Painting|Visual Arts|Craft|Conceptual',
       'Painting|Craft|Mixed Media|2D Composition',
       'Visual Arts|Craft|Mixed Media|Conceptual|Mosaic painting',
       'Craft|Drawings|Conceptual|2D Composition',
       'Craft|Mixed Media|Conceptual|Mosaic painting|2D Composition',
       'Video',
       'Fashion Desigining|Fashion Illustration|Pattern Cutting|Fashion Communication',
       'Biotechnology|Animal Biotechnology',
       'Fashion Desigining|Pattern & Culture|Fashion Trends|Fashion Portfoilio',
       'Sketch Video',
       'Fashion Desigining|Pattern & Culture|Fashion Textile|Fashion Trends',
       'Test', 'Professionalism', 'Art', 'Science;Technology',
       'Art; Science',
       'Fashion Design|Illustration|Watercolours|Drawings',
       'Drawings|Fashion Design|Illustration|Watercolours',
       'Fashion Design|Illustration|Watercolours',
       'Drawings|Fashion Design|Mixed Media|Conceptual|Illustration|Pen and ink|Watercolours',
       'Fashion Design|Illustration|Conceptual|Watercolours|Pen and ink',
       'Artistic design|Logo Design|Graphic|Illustration',
       'Visual Arts|Graphic Design|Artistic design|Graphic|Illustration',
       'Learning', 'Photography|Architecture|Visual Arts|Graphic Design',
       'Photography|Architecture|Visual Arts|Graphic Design|Artistic design|Graphic|Logo Design',
       'Visual Arts|Graphic Design|2D Composition|Logo Design',
       'Artistic design',
       'Literature|Stories|Fictions|Movements in Literature',
       'Technology',
       'Computer Technology|Computation|Computer Application|Cloud Computing',
       'Visual Arts|Calligraphy|Pen and ink',
       'Mixed Media|Calligraphy|Pen and ink', 'Typography|Pen and ink',
       'Typography|Calligraphy|Pen and ink',
       'Calligraphy|Typography|Pen and ink', 'Calligraphy|Pen and ink',
       'Mass Media|Media And Society', 'Science; Technology'],
      dtype=object)

In [37]:
post['category'] = post['category'].fillna('random')

In [38]:
cat = {}
for i in post['category']:
    cat.update({i: []})
    for j in i.split('|'):
        cat[i].append(j)
print(cat)

{'Plant Biotechnology': ['Plant Biotechnology'], 'Artificial Intelligence|Machine Learning|Information Technology': ['Artificial Intelligence', 'Machine Learning', 'Information Technology'], 'Operating Systems': ['Operating Systems'], 'Drawings': ['Drawings'], 'Competition Laws': ['Competition Laws'], 'Eco System': ['Eco System'], 'Economic Policies': ['Economic Policies'], 'Graphic|Graphic Design': ['Graphic', 'Graphic Design'], 'Painting': ['Painting'], 'Pen and ink': ['Pen and ink'], 'Computer Technology|Information Technology': ['Computer Technology', 'Information Technology'], 'Drawings|Painting': ['Drawings', 'Painting'], 'Graphic Design|Visual Arts|Illustration|Graphic': ['Graphic Design', 'Visual Arts', 'Illustration', 'Graphic'], 'Drawings|Calligraphy': ['Drawings', 'Calligraphy'], 'Photography': ['Photography'], 'Empowerment': ['Empowerment'], 'random': ['random'], 'Video editing': ['Video editing'], 'Inorganic Chemistry': ['Inorganic Chemistry'], 'Programming languages': ['Programming languages'], 'Conceptual|Graphic Design': ['Conceptual', 'Graphic Design'], 'HR Management': ['HR Management'], 'Human Resources|HR Management': ['Human Resources', 'HR Management'], 'Mass Media|International Relations': ['Mass Media', 'International Relations'], 'Sculptures|Artistic design': ['Sculptures', 'Artistic design'], 'Fashion Design|Ceramics|Artistic design': ['Fashion Design', 'Ceramics', 'Artistic design'], 'Craft|Artistic design': ['Craft', 'Artistic design'], 'Fashion Design|Visual Arts|Conceptual|Artistic design': ['Fashion Design', 'Visual Arts', 'Conceptual', 'Artistic design'], 'Photography|Fashion Design|Visual Arts|Graphic Design|Artistic design': ['Photography', 'Fashion Design', 'Visual Arts', 'Graphic Design', 'Artistic design'], 'Fashion Design|Visual Arts|Graphic Design|Artistic design|Graphic|Illustration': ['Fashion Design', 'Visual Arts', 'Graphic Design', 'Artistic design', 'Graphic', 'Illustration'], 'Mathematics|Linear Algebra': ['Mathematics', 'Linear Algebra'], 'Electronics & electrical Technology|Electrical Machines': ['Electronics & electrical Technology', 'Electrical Machines'], 'Auditing|Internal Audit': ['Auditing', 'Internal Audit'], 'E Commerce|E Transactions': ['E Commerce', 'E Transactions'], 'Computer Technology|Computation': ['Computer Technology', 'Computation'], 'Auditing|Internal Financial Control': ['Auditing', 'Internal Financial Control'], 'Taxation|Custom Laws': ['Taxation', 'Custom Laws'], 'Auditing|Audit Evidence': ['Auditing', 'Audit Evidence'], 'Taxation|GST': ['Taxation', 'GST'], 'Taxation|Direct Tax': ['Taxation', 'Direct Tax'], 'Auditing|Secratarial Audit': ['Auditing', 'Secratarial Audit'], 'Banking|Banking Companies': ['Banking', 'Banking Companies'], 'Banking|Banking Technology': ['Banking', 'Banking Technology'], 'Auditing|Audit Remark': ['Auditing', 'Audit Remark'], 'Auditing|Cost Audit': ['Auditing', 'Cost Audit'], 'Auditing|Statuary Audit': ['Auditing', 'Statuary Audit'], 'Computer Technology|Programming languages': ['Computer Technology', 'Programming languages'], 'Legal Studies|Legal System': ['Legal Studies', 'Legal System'], 'Sports Coaching|Sports Law': ['Sports Coaching', 'Sports Law'], 'Economics|Economics Sociology': ['Economics', 'Economics Sociology'], 'Economics|Revenue Concept': ['Economics', 'Revenue Concept'], 'Human Rights|Rights and Duties': ['Human Rights', 'Rights and Duties'], 'Sociology|Sociology of Religion': ['Sociology', 'Sociology of Religion'], 'Sociology|Sociology in India': ['Sociology', 'Sociology in India'], 'Political Science|International Politics': ['Political Science', 'International Politics'], 'Political Science|Colonialism In India': ['Political Science', 'Colonialism In India'], 'Legal Studies|Labor Law': ['Legal Studies', 'Labor Law'], 'Computer Technology|Design and Analysis of Algorithms|Programming languages': ['Computer Technology', 'Design and Analysis of Algorithms', 'Programming languages'], 'Computer Technology|Computer Application|Programming languages|Information Technology': ['Computer Technology', 'Computer Application', 'Programming languages', 'Information Technology'], 'Graphics|Computer Creation': ['Graphics', 'Computer Creation'], 'E Commerce|Other Online Platforms': ['E Commerce', 'Other Online Platforms'], 'Drawing': ['Drawing'], 'Drawings|Artistic design': ['Drawings', 'Artistic design'], 'Drawings|Artistic design|Illustration': ['Drawings', 'Artistic design', 'Illustration'], 'E Commerce|Shopping Platform|Other Online Platforms': ['E Commerce', 'Shopping Platform', 'Other Online Platforms'], 'Computer Technology|Hardware|Information Technology': ['Computer Technology', 'Hardware', 'Information Technology'], 'Computer Technology|Computation|Computer Application': ['Computer Technology', 'Computation', 'Computer Application'], 'Business|Business Skills': ['Business', 'Business Skills'], 'Computer Technology|Computer Application|Hardware|Information Technology': ['Computer Technology', 'Computer Application', 'Hardware', 'Information Technology'], 'Computer Technology|Computer Application': ['Computer Technology', 'Computer Application'], 'Computer Technology|Mobile Applications': ['Computer Technology', 'Mobile Applications'], 'Computer Technology|Computer Application|Operating Systems': ['Computer Technology', 'Computer Application', 'Operating Systems'], 'Computer Technology|Information Technology|Computer Application': ['Computer Technology', 'Information Technology', 'Computer Application'], 'Computer Technology|Computer Application|Information Technology': ['Computer Technology', 'Computer Application', 'Information Technology'], 'Communication|Basics of Communiaction': ['Communication', 'Basics of Communiaction'], 'Drawings|Painting|Visual Arts|Graphic Design|Prints|Illustration': ['Drawings', 'Painting', 'Visual Arts', 'Graphic Design', 'Prints', 'Illustration'], 'Drawings|Visual Arts|Painting|Graphic Design|Artistic design|Illustration': ['Drawings', 'Visual Arts', 'Painting', 'Graphic Design', 'Artistic design', 'Illustration'], 'Computer Technology|Artificial Intelligence': ['Computer Technology', 'Artificial Intelligence'], 'Marketing|Advertising': ['Marketing', 'Advertising'], 'Political Science|Political Thought': ['Political Science', 'Political Thought'], 'Accounting|Fundamental Of Accounting': ['Accounting', 'Fundamental Of Accounting'], 'Mixed Media': ['Mixed Media'], 'Management|Team Mangememnt': ['Management', 'Team Mangememnt'], 'Business|Corporate Social Responsibilities': ['Business', 'Corporate Social Responsibilities'], 'Philosophy|Applied Ethics': ['Philosophy', 'Applied Ethics'], 'Human Resources|Performance In Organization|Organizational Behaviour|HR Management': ['Human Resources', 'Performance In Organization', 'Organizational Behaviour', 'HR Management'], 'Fashion Desigining|Fashion Textile|Fashion Manufacturing|Fashion Techniques|Garment Production|Garment Technology': ['Fashion Desigining', 'Fashion Textile', 'Fashion Manufacturing', 'Fashion Techniques', 'Garment Production', 'Garment Technology'], 'Marketing|Promotion And Distribution Decisions': ['Marketing', 'Promotion And Distribution Decisions'], 'Biotechnology|Genetic Engineering': ['Biotechnology', 'Genetic Engineering'], 'Physiology|Neurology': ['Physiology', 'Neurology'], 'Mass Media|Indian Government': ['Mass Media', 'Indian Government'], 'Physiology|Osteology': ['Physiology', 'Osteology'], 'Physiology|Cardiology': ['Physiology', 'Cardiology'], 'Zoology|Ecology': ['Zoology', 'Ecology'], 'Computer Technology|Cloud Computing': ['Computer Technology', 'Cloud Computing'], 'Physiology|Radiology': ['Physiology', 'Radiology'], 'Computer Technology|Operating Systems': ['Computer Technology', 'Operating Systems'], 'Biotechnology|Molecular Biology': ['Biotechnology', 'Molecular Biology'], 'Physiology|Gastroenterology|Cardiology': ['Physiology', 'Gastroenterology', 'Cardiology'], 'Philosophy|Logic': ['Philosophy', 'Logic'], 'Watercolours': ['Watercolours'], 'Drawings|Watercolours': ['Drawings', 'Watercolours'], 'Mixed Media|Conceptual': ['Mixed Media', 'Conceptual'], 'Drawings|Painting|Watercolours': ['Drawings', 'Painting', 'Watercolours'], 'Visual Arts': ['Visual Arts'], 'Conceptual': ['Conceptual'], 'Tapestry': ['Tapestry'], 'Calligraphy': ['Calligraphy'], 'Human Resources|Performance In Organization': ['Human Resources', 'Performance In Organization'], 'Computer Technology|Robotics|Data Science|Information Technology|Artificial Intelligence': ['Computer Technology', 'Robotics', 'Data Science', 'Information Technology', 'Artificial Intelligence'], 'Philosophy|Public Philosophy': ['Philosophy', 'Public Philosophy'], 'Digital Marketing': ['Digital Marketing'], 'Mass Media|Videography': ['Mass Media', 'Videography'], 'Drawings|Painting|Visual Arts|Artistic design|Watercolours|Acrylics': ['Drawings', 'Painting', 'Visual Arts', 'Artistic design', 'Watercolours', 'Acrylics'], 'Biotechnology|Plant Biotechnology': ['Biotechnology', 'Plant Biotechnology'], 'Sports Coaching|Sports Event': ['Sports Coaching', 'Sports Event'], 'Political Science|Government and Politics': ['Political Science', 'Government and Politics'], 'Geography|Physical Geography': ['Geography', 'Physical Geography'], 'Computer Technology|Data Science': ['Computer Technology', 'Data Science'], 'Computer Technology|Machine Learning': ['Computer Technology', 'Machine Learning'], 'Graphic Design': ['Graphic Design'], 'Graphic Design|Visual Arts': ['Graphic Design', 'Visual Arts'], 'Education': ['Education'], 'Business|Business Organisation': ['Business', 'Business Organisation'], 'Zoology|Environmental Biology': ['Zoology', 'Environmental Biology'], 'Human Rights|Fundamental Rights': ['Human Rights', 'Fundamental Rights'], 'Computer Technology|Design and Analysis of Algorithms': ['Computer Technology', 'Design and Analysis of Algorithms'], 'Marketing|Marketing Management': ['Marketing', 'Marketing Management'], 'Accounting|Partnership Accounting|Corporate Accounting|Accounting Theory And Practices': ['Accounting', 'Partnership Accounting', 'Corporate Accounting', 'Accounting Theory And Practices'], 'Legal Studies|Income Tax Laws': ['Legal Studies', 'Income Tax Laws'], 'Graphics|Articulation|Computer Creation': ['Graphics', 'Articulation', 'Computer Creation'], 'Archeology|Human Prehistory': ['Archeology', 'Human Prehistory'], 'Business|Start Ups|Entreperneurship|Business Strategies|Venture Capitalist|Business Planning': ['Business', 'Start Ups', 'Entreperneurship', 'Business Strategies', 'Venture Capitalist', 'Business Planning'], 'Geography|Indian Geography': ['Geography', 'Indian Geography'], 'E Commerce|Shopping Platform|Other Online Platforms|Digital India': ['E Commerce', 'Shopping Platform', 'Other Online Platforms', 'Digital India'], 'Business|Bio-entrepreneurship': ['Business', 'Bio-entrepreneurship'], 'Literature|Stories': ['Literature', 'Stories'], 'History|Indian History': ['History', 'Indian History'], 'ViDEO': ['ViDEO'], 'Management|Business Management': ['Management', 'Business Management'], 'Visual Arts|Photography': ['Visual Arts', 'Photography'], 'Social Work|Health Education': ['Social Work', 'Health Education'], 'Social Work|Social Tech': ['Social Work', 'Social Tech'], 'Social Work|Humanities': ['Social Work', 'Humanities'], 'Photography|Visual Arts': ['Photography', 'Visual Arts'], 'Accounting|Financial Accounting': ['Accounting', 'Financial Accounting'], 'Psycholgy|Social Psychology': ['Psycholgy', 'Social Psychology'], 'Photography|Conceptual': ['Photography', 'Conceptual'], 'Physics|Instrumentation': ['Physics', 'Instrumentation'], 'Craft work': ['Craft work'], 'Social Work|Social Interventions|Substance Abuse': ['Social Work', 'Social Interventions', 'Substance Abuse'], 'Economics|Indian Economy': ['Economics', 'Indian Economy'], 'Social Work|Substance Abuse|Social Interventions|Humanities': ['Social Work', 'Substance Abuse', 'Social Interventions', 'Humanities'], 'Social Work|Social Interventions|Substance Abuse|Health Education': ['Social Work', 'Social Interventions', 'Substance Abuse', 'Health Education'], 'Social Work|Humanities|Social Interventions': ['Social Work', 'Humanities', 'Social Interventions'], 'Finance|Financial Analysis': ['Finance', 'Financial Analysis'], 'Architecture': ['Architecture'], 'Photography|Architecture|Painting': ['Photography', 'Architecture', 'Painting'], 'Computer Technology|Cloud Computing|Artificial Intelligence|Information Technology|Programming languages': ['Computer Technology', 'Cloud Computing', 'Artificial Intelligence', 'Information Technology', 'Programming languages'], 'Computer Technology|Design and Analysis of Algorithms|Web designing|Database Management|Artificial Intelligence': ['Computer Technology', 'Design and Analysis of Algorithms', 'Web designing', 'Database Management', 'Artificial Intelligence'], 'Literature|Movements in Literature': ['Literature', 'Movements in Literature'], 'Physics|Atomic Physics|Energy Physics|Quantum Mecahnics|Instrumentation': ['Physics', 'Atomic Physics', 'Energy Physics', 'Quantum Mecahnics', 'Instrumentation'], 'Business|Business Strategies|Venture Capitalist': ['Business', 'Business Strategies', 'Venture Capitalist'], 'Photography|Architecture|Illustration': ['Photography', 'Architecture', 'Illustration'], 'Photography|Architecture': ['Photography', 'Architecture'], 'Human Rights|Fundamental Rights|Protection & Enforcement': ['Human Rights', 'Fundamental Rights', 'Protection & Enforcement'], 'Environment Studies|Pollution|Environmental Biology': ['Environment Studies', 'Pollution', 'Environmental Biology'], 'Photography|Conceptual|Illustration': ['Photography', 'Conceptual', 'Illustration'], 'Physics|Quantum Mecahnics|Industrial Instrumentation|Atomic Physics|Nuclear & Particle Physics|Energy Physics': ['Physics', 'Quantum Mecahnics', 'Industrial Instrumentation', 'Atomic Physics', 'Nuclear & Particle Physics', 'Energy Physics'], 'Biotechnology|Environmental Biotechnology': ['Biotechnology', 'Environmental Biotechnology'], 'Legal Studies|Alternate Dispute Resolution|International Treaties|International Agreement': ['Legal Studies', 'Alternate Dispute Resolution', 'International Treaties', 'International Agreement'], 'Marketing|Principles Of Marketing|Marketing Research Methadology|Marketing Management|International Marketing': ['Marketing', 'Principles Of Marketing', 'Marketing Research Methadology', 'Marketing Management', 'International Marketing'], 'Sculptures': ['Sculptures'], 'Psycholgy|Child Development': ['Psycholgy', 'Child Development'], 'Economics|Economic Policies|Break even Point|Foreign Economy': ['Economics', 'Economic Policies', 'Break even Point', 'Foreign Economy'], 'Psycholgy|Psychological Growth': ['Psycholgy', 'Psychological Growth'], 'Management|Business Management|Technology Mangement|Managerial Activity|Creative And Lateral Management': ['Management', 'Business Management', 'Technology Mangement', 'Managerial Activity', 'Creative And Lateral Management'], 'Business': ['Business'], 'Business|Business Strategies|Business Enviorment|New Venture Planning|Foreign Business|Business Organisation': ['Business', 'Business Strategies', 'Business Enviorment', 'New Venture Planning', 'Foreign Business', 'Business Organisation'], 'Marketing|Principles Of Marketing|International Marketing|Promotion And Distribution Decisions': ['Marketing', 'Principles Of Marketing', 'International Marketing', 'Promotion And Distribution Decisions'], 'Social Work|NGO': ['Social Work', 'NGO'], 'Fine Arts|Painting': ['Fine Arts', 'Painting'], 'Legal Studies|Legal System|Legal Tradition|Nationality Law|Government Law': ['Legal Studies', 'Legal System', 'Legal Tradition', 'Nationality Law', 'Government Law'], 'Business|Entreperneurship|Venture Capitalist|Business Enviorment|Start Ups|Business Planning|New Venture Planning': ['Business', 'Entreperneurship', 'Venture Capitalist', 'Business Enviorment', 'Start Ups', 'Business Planning', 'New Venture Planning'], 'Legal Studies|Company Law|Legal System|Banking Law': ['Legal Studies', 'Company Law', 'Legal System', 'Banking Law'], 'Computer Technology|Web designing|Artificial Intelligence|Computer Application|Machine Learning|Frontend Development': ['Computer Technology', 'Web designing', 'Artificial Intelligence', 'Computer Application', 'Machine Learning', 'Frontend Development'], 'Music': ['Music'], 'Sculptures|Wood Crafts|Craft|Wood carving': ['Sculptures', 'Wood Crafts', 'Craft', 'Wood carving'], 'Fashion Design': ['Fashion Design'], 'Painting|Craft|Artistic design': ['Painting', 'Craft', 'Artistic design'], '2D Composition|Watercolours|Painting': ['2D Composition', 'Watercolours', 'Painting'], 'Painting|Watercolours|2D Composition': ['Painting', 'Watercolours', '2D Composition'], 'Visual Arts|Craft|Conceptual': ['Visual Arts', 'Craft', 'Conceptual'], 'Painting|Visual Arts|Craft|Conceptual': ['Painting', 'Visual Arts', 'Craft', 'Conceptual'], 'Painting|Craft|Mixed Media|2D Composition': ['Painting', 'Craft', 'Mixed Media', '2D Composition'], 'Visual Arts|Craft|Mixed Media|Conceptual|Mosaic painting': ['Visual Arts', 'Craft', 'Mixed Media', 'Conceptual', 'Mosaic painting'], 'Craft|Drawings|Conceptual|2D Composition': ['Craft', 'Drawings', 'Conceptual', '2D Composition'], 'Craft|Mixed Media|Conceptual|Mosaic painting|2D Composition': ['Craft', 'Mixed Media', 'Conceptual', 'Mosaic painting', '2D Composition'], 'Video': ['Video'], 'Fashion Desigining|Fashion Illustration|Pattern Cutting|Fashion Communication': ['Fashion Desigining', 'Fashion Illustration', 'Pattern Cutting', 'Fashion Communication'], 'Biotechnology|Animal Biotechnology': ['Biotechnology', 'Animal Biotechnology'], 'Fashion Desigining|Pattern & Culture|Fashion Trends|Fashion Portfoilio': ['Fashion Desigining', 'Pattern & Culture', 'Fashion Trends', 'Fashion Portfoilio'], 'Sketch Video': ['Sketch Video'], 'Fashion Desigining|Pattern & Culture|Fashion Textile|Fashion Trends': ['Fashion Desigining', 'Pattern & Culture', 'Fashion Textile', 'Fashion Trends'], 'Test': ['Test'], 'Professionalism': ['Professionalism'], 'Art': ['Art'], 'Science;Technology': ['Science;Technology'], 'Art; Science': ['Art; Science'], 'Fashion Design|Illustration|Watercolours|Drawings': ['Fashion Design', 'Illustration', 'Watercolours', 'Drawings'], 'Drawings|Fashion Design|Illustration|Watercolours': ['Drawings', 'Fashion Design', 'Illustration', 'Watercolours'], 'Fashion Design|Illustration|Watercolours': ['Fashion Design', 'Illustration', 'Watercolours'], 'Drawings|Fashion Design|Mixed Media|Conceptual|Illustration|Pen and ink|Watercolours': ['Drawings', 'Fashion Design', 'Mixed Media', 'Conceptual', 'Illustration', 'Pen and ink', 'Watercolours'], 'Fashion Design|Illustration|Conceptual|Watercolours|Pen and ink': ['Fashion Design', 'Illustration', 'Conceptual', 'Watercolours', 'Pen and ink'], 'Artistic design|Logo Design|Graphic|Illustration': ['Artistic design', 'Logo Design', 'Graphic', 'Illustration'], 'Visual Arts|Graphic Design|Artistic design|Graphic|Illustration': ['Visual Arts', 'Graphic Design', 'Artistic design', 'Graphic', 'Illustration'], 'Learning': ['Learning'], 'Photography|Architecture|Visual Arts|Graphic Design': ['Photography', 'Architecture', 'Visual Arts', 'Graphic Design'], 'Photography|Architecture|Visual Arts|Graphic Design|Artistic design|Graphic|Logo Design': ['Photography', 'Architecture', 'Visual Arts', 'Graphic Design', 'Artistic design', 'Graphic', 'Logo Design'], 'Visual Arts|Graphic Design|2D Composition|Logo Design': ['Visual Arts', 'Graphic Design', '2D Composition', 'Logo Design'], 'Artistic design': ['Artistic design'], 'Literature|Stories|Fictions|Movements in Literature': ['Literature', 'Stories', 'Fictions', 'Movements in Literature'], 'Technology': ['Technology'], 'Computer Technology|Computation|Computer Application|Cloud Computing': ['Computer Technology', 'Computation', 'Computer Application', 'Cloud Computing'], 'Visual Arts|Calligraphy|Pen a

In [49]:
update_data = []
for i in cat:
    dummy = post[post['category'] == i]
    id = dummy['_id'].values[0]
    title = dummy['title'].values[0]
    post_type = dummy[' post_type'].values[0]
    for j in cat[i]:
        dict1 = {}
        dict1.update({'_id':id})
        dict1.update({'title': title})
        dict1.update({'category': j})
        dict1.update({' post_type': post_type})
        update_data.append(dict1)

In [50]:
update_data

[{'_id': '5d62abaa65218653a132c956',
  'title': 'hello there',
  'category': 'Plant Biotechnology',
  ' post_type': 'blog'},
 {'_id': '5d6d39567fa40e1417a4931c',
  'title': 'Ml and AI',
  'category': 'Artificial Intelligence',
  ' post_type': 'blog'},
 {'_id': '5d6d39567fa40e1417a4931c',
  'title': 'Ml and AI',
  'category': 'Machine Learning',
  ' post_type': 'blog'},
 {'_id': '5d6d39567fa40e1417a4931c',
  'title': 'Ml and AI',
  'category': 'Information Technology',
  ' post_type': 'blog'},
 {'_id': '5d7d23315720533e15c3b1ee',
  'title': 'What is an Operating System ?',
  'category': 'Operating Systems',
  ' post_type': 'blog'},
 {'_id': '5d7d405e5720533e15c3b1f3',
  'title': 'Lord Shiva',
  'category': 'Drawings',
  ' post_type': 'artwork'},
 {'_id': '5d80dfbc6c53455f896e600e',
  'title': 'How Competition law evolved?',
  'category': 'Competition Laws',
  ' post_type': 'blog'},
 {'_id': '5d9b3514979d5962253c2f90',
  'title': 'Biodiversity',
  'category': 'Eco System',
  ' post_type': 'blog'},
 {'_id': '5d9b950768671220a1b2b153',
  'title': 'Economic policy',
  'category': 'Economic Policies',
  ' post_type': 'blog'},
 {'_id': '5da745b6019399436815c4cd',
  'title': 'Corporate design',
  'category': 'Graphic',
  ' post_type': 'artwork'},
 {'_id': '5da745b6019399436815c4cd',
  'title': 'Corporate design',
  'category': 'Graphic Design',
  ' post_type': 'artwork'},
 {'_id': '5dada798610ba040fbfdf58b',
  'title': 'Smart City',
  'category': 'Painting',
  ' post_type': 'artwork'},
 {'_id': '5dada82f610ba040fbfdf58e',
  'title': 'Om Namah Shivaay',
  'category': 'Pen and ink',
  ' post_type': 'artwork'},
 {'_id': '5dadf6ae610ba040fbfdf5c8',
  'title': 'MIS',
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5dadf6ae610ba040fbfdf5c8',
  'title': 'MIS',
  'category': 'Information Technology',
  ' post_type': 'blog'},
 {'_id': '5db2a7d099cbb90e4339c734',
  'title': 'Portrait art',
  'category': 'Drawings',
  ' post_type': 'artwork'},
 {'_id': '5db2a7d099cbb90e4339c734',
  'title': 'Portrait art',
  'category': 'Painting',
  ' post_type': 'artwork'},
 {'_id': '5dbc622a99cbb90e4339c7f6',
  'title': 'Best friend',
  'category': 'Graphic Design',
  ' post_type': 'artwork'},
 {'_id': '5dbc622a99cbb90e4339c7f6',
  'title': 'Best friend',
  'category': 'Visual Arts',
  ' post_type': 'artwork'},
 {'_id': '5dbc622a99cbb90e4339c7f6',
  'title': 'Best friend',
  'category': 'Illustration',
  ' post_type': 'artwork'},
 {'_id': '5dbc622a99cbb90e4339c7f6',
  'title': 'Best friend',
  'category': 'Graphic',
  ' post_type': 'artwork'},
 {'_id': '5dbc631f99cbb90e4339c7fd',
  'title': 'Calligraphy',
  'category': 'Drawings',
  ' post_type': 'artwork'},
 {'_id': '5dbc631f99cbb90e4339c7fd',
  'title': 'Calligraphy',
  'category': 'Calligraphy',
  ' post_type': 'artwork'},
 {'_id': '5dc065ca24b883670268772f',
  'title': 'Colours of pushkar.',
  'category': 'Photography',
  ' post_type': 'artwork'},
 {'_id': '5dd1751db802e41ed198b680',
  'title': 'Marital Rape - Rape is Rape',
  'category': 'Empowerment',
  ' post_type': 'blog'},
 {'_id': '5ddeb6e80eb5e25a8a07f065',
  'title': 'Library Managment System: Software Requirement Specification (SRS)',
  'category': 'random',
  ' post_type': 'project'},
 {'_id': '5de8d73249e8203ff9219a74',
  'title': 'Promotional video.',
  'category': 'Video editing',
  ' post_type': 'skill'},
 {'_id': '5dea816a42a8854bf6eaba89',
  'title': 'The Periodic Table',
  'category': 'Inorganic Chemistry',
  ' post_type': 'blog'},
 {'_id': '5e04fb252a37d20505da2a2b',
  'title': 'Python 3 Programming Introduction',
  'category': 'Programming languages',
  ' post_type': 'blog'},
 {'_id': '5e1029f22a37d20505da2a79',
  'title': 'Chat App UI Desgin',
  'category': 'Conceptual',
  ' post_type': 'artwork'},
 {'_id': '5e1029f22a37d20505da2a79',
  'title': 'Chat App UI Desgin',
  'category': 'Graphic Design',
  ' post_type': 'artwork'},
 {'_id': '5e27002d2a37d20505da2c13',
  'title': 'Workforce Diversity as a Challenge',
  'category': 'HR Management',
  ' post_type': 'blog'},
 {'_id': '5e2867f6025ae20886de205a',
  'title': 'Human Resource Management',
  'category': 'Human Resources',
  ' post_type': 'blog'},
 {'_id': '5e2867f6025ae20886de205a',
  'title': 'Human Resource Management',
  'category': 'HR Management',
  ' post_type': 'blog'},
 {'_id': '5e294fd1c85ab714a7da6643',
  'title': 'Personal growth',
  'category': 'Mass Media',
  ' post_type': 'blog'},
 {'_id': '5e294fd1c85ab714a7da6643',
  'title': 'Personal growth',
  'category': 'International Relations',
  ' post_type': 'blog'},
 {'_id': '5e2d36ebc85ab714a7da66d1',
  'title': 'CONTOURING CLAY',
  'category': 'Sculptures',
  ' post_type': 'artwork'},
 {'_id': '5e2d36ebc85ab714a7da66d1',
  'title': 'CONTOURING CLAY',
  'category': 'Artistic design',
  ' post_type': 'artwork'},
 {'_id': '5e2d3fbfc85ab714a7da66d5',
  'title': 'Multipurpose Jewel',
  'category': 'Fashion Design',
  ' post_type': 'artwork'},
 {'_id': '5e2d3fbfc85ab714a7da66d5',
  'title': 'Multipurpose Jewel',
  'category': 'Ceramics',
  ' post_type': 'artwork'},
 {'_id': '5e2d3fbfc85ab714a7da66d5',
  'title': 'Multipurpose Jewel',
  'category': 'Artistic design',
  ' post_type': 'artwork'},
 {'_id': '5e2d447dc85ab714a7da66d7',
  'title': 'Traditional and Modern Sports',
  'category': 'Craft',
  ' post_type': 'artwork'},
 {'_id': '5e2d447dc85ab714a7da66d7',
  'title': 'Traditional and Modern Sports',
  'category': 'Artistic design',
  ' post_type': 'artwork'},
 {'_id': '5e2d4737c85ab714a7da66d9',
  'title': 'LGBT PRIDE',
  'category': 'Fashion Design',
  ' post_type': 'artwork'},
 {'_id': '5e2d4737c85ab714a7da66d9',
  'title': 'LGBT PRIDE',
  'category': 'Visual Arts',
  ' post_type': 'artwork'},
 {'_id': '5e2d4737c85ab714a7da66d9',
  'title': 'LGBT PRIDE',
  'category': 'Conceptual',
  ' post_type': 'artwork'},
 {'_id': '5e2d4737c85ab714a7da66d9',
  'title': 'LGBT PRIDE',
  'category': 'Artistic design',
  ' post_type': 'artwork'},
 {'_id': '5e2d4d63c85ab714a7da66db',
  'title': 'Magazine Cover Redefined',
  'category': 'Photography',
  ' post_type': 'artwork'},
 {'_id': '5e2d4d63c85ab714a7da66db',
  'title': 'Magazine Cover Redefined',
  'category': 'Fashion Design',
  ' post_type': 'artwork'},
 {'_id': '5e2d4d63c85ab714a7da66db',
  'title': 'Magazine Cover Redefined',
  'category': 'Visual Arts',
  ' post_type': 'artwork'},
 {'_id': '5e2d4d63c85ab714a7da66db',
  'title': 'Magazine Cover Redefined',
  'category': 'Graphic Design',
  ' post_type': 'artwork'},
 {'_id': '5e2d4d63c85ab714a7da66db',
  'title': 'Magazine Cover Redefined',
  'category': 'Artistic design',
  ' post_type': 'artwork'},
 {'_id': '5e2d516fc85ab714a7da66dd',
  'title': "'The Virtual ME'",
  'category': 'Fashion Design',
  ' post_type': 'artwork'},
 {'_id': '5e2d516fc85ab714a7da66dd',
  'title': "'The Virtual ME'",
  'category': 'Visual Arts',
  ' post_type': 'artwork'},
 {'_id': '5e2d516fc85ab714a7da66dd',
  'title': "'The Virtual ME'",
  'category': 'Graphic Design',
  ' post_type': 'artwork'},
 {'_id': '5e2d516fc85ab714a7da66dd',
  'title': "'The Virtual ME'",
  'category': 'Artistic design',
  ' post_type': 'artwork'},
 {'_id': '5e2d516fc85ab714a7da66dd',
  'title': "'The Virtual ME'",
  'category': 'Graphic',
  ' post_type': 'artwork'},
 {'_id': '5e2d516fc85ab714a7da66dd',
  'title': "'The Virtual ME'",
  'category': 'Illustration',
  ' post_type': 'artwork'},
 {'_id': '5e2f1811c85ab714a7da670d',
  'title': 'Abacus',
  'category': 'Mathematics',
  ' post_type': 'blog'},
 {'_id': '5e2f1811c85ab714a7da670d',
  'title': 'Abacus',
  'category': 'Linear Algebra',
  ' post_type': 'blog'},
 {'_id': '5e31a591c85ab714a7da6760',
  'title': 'Will AI replace humans intellectual work?',
  'category': 'Electronics & electrical Technology',
  ' post_type': 'blog'},
 {'_id': '5e31a591c85ab714a7da6760',
  'title': 'Will AI replace humans intellectual work?',
  'category': 'Electrical Machines',
  ' post_type': 'blog'},
 {'_id': '5e36db70eab55d319938a6cc',
  'title': 'HOW INTERNAL AUDIT WORKS',
  'category': 'Auditing',
  ' post_type': 'blog'},
 {'_id': '5e36db70eab55d319938a6cc',
  'title': 'HOW INTERNAL AUDIT WORKS',
  'category': 'Internal Audit',
  ' post_type': 'blog'},
 {'_id': '5e36e7baeab55d319938a6d1',
  'title': 'E-Commerce',
  'category': 'E Commerce',
  ' post_type': 'blog'},
 {'_id': '5e36e7baeab55d319938a6d1',
  'title': 'E-Commerce',
  'category': 'E Transactions',
  ' post_type': 'blog'},
 {'_id': '5e372ee2eab55d319938a6ed',
  'title': 'SEO (Search Engine Optimization)',
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5e372ee2eab55d319938a6ed',
  'title': 'SEO (Search Engine Optimization)',
  'category': 'Computation',
  ' post_type': 'blog'},
 {'_id': '5e37c087eab55d319938a700',
  'title': 'IMPORTANCE OF INTERNAL FINANCIAL CONTROL',
  'category': 'Auditing',
  ' post_type': 'blog'},
 {'_id': '5e37c087eab55d319938a700',
  'title': 'IMPORTANCE OF INTERNAL FINANCIAL CONTROL',
  'category': 'Internal Financial Control',
  ' post_type': 'blog'},
 {'_id': '5e37c301eab55d319938a701',
  'title': 'Custom laws',
  'category': 'Taxation',
  ' post_type': 'blog'},
 {'_id': '5e37c301eab55d319938a701',
  'title': 'Custom laws',
  'category': 'Custom Laws',
  ' post_type': 'blog'},
 {'_id': '5e37c78aeab55d319938a703',
  'title': 'WHY AUDIT EVIDENCE IS NECESSARY?',
  'category': 'Auditing',
  ' post_type': 'blog'},
 {'_id': '5e37c78aeab55d319938a703',
  'title': 'WHY AUDIT EVIDENCE IS NECESSARY?',
  'category': 'Audit Evidence',
  ' post_type': 'blog'},
 {'_id': '5e37ce10eab55d319938a710',
  'title': 'GOODS & SERVICE TAX (GST)',
  'category': 'Taxation',
  ' post_type': 'blog'},
 {'_id': '5e37ce10eab55d319938a710',
  'title': 'GOODS & SERVICE TAX (GST)',
  'category': 'GST',
  ' post_type': 'blog'},
 {'_id': '5e37d08ceab55d319938a711',
  'title': 'DIRECT TAX',
  'category': 'Taxation',
  ' post_type': 'blog'},
 {'_id': '5e37d08ceab55d319938a711',
  'title': 'DIRECT TAX',
  'category': 'Direct Tax',
  ' post_type': 'blog'},
 {'_id': '5e37d1afeab55d319938a712',
  'title': 'SECRETARIAL AUDIT',
  'category': 'Auditing',
  ' post_type': 'blog'},
 {'_id': '5e37d1afeab55d319938a712',
  'title': 'SECRETARIAL AUDIT',
  'category': 'Secratarial Audit',
  ' post_type': 'blog'},
 {'_id': '5e37d490eab55d319938a713',
  'title': 'ROLE OF BANKING COMPANIES IN INDIA',
  'category': 'Banking',
  ' post_type': 'blog'},
 {'_id': '5e37d490eab55d319938a713',
  'title': 'ROLE OF BANKING COMPANIES IN INDIA',
  'category': 'Banking Companies',
  ' post_type': 'blog'},
 {'_id': '5e37d699eab55d319938a71a',
  'title': 'WHAT NEW TECHNOLOGY DOES BANKS ARE USING TODAY?',
  'category': 'Banking',
  ' post_type': 'blog'},
 {'_id': '5e37d699eab55d319938a71a',
  'title': 'WHAT NEW TECHNOLOGY DOES BANKS ARE USING TODAY?',
  'category': 'Banking Technology',
  ' post_type': 'blog'},
 {'_id': '5e37d8c9eab55d319938a71e',
  'title': 'AUDIT REMARK',
  'category': 'Auditing',
  ' post_type': 'blog'},
 {'_id': '5e37d8c9eab55d319938a71e',
  'title': 'AUDIT REMARK',
  'category': 'Audit Remark',
  ' post_type': 'blog'},
 {'_id': '5e37d9eaeab55d319938a71f',
  'title': 'WHY COST AUDIT IS IMPORTANT FOR A COMPANY',
  'category': 'Auditing',
  ' post_type': 'blog'},
 {'_id': '5e37d9eaeab55d319938a71f',
  'title': 'WHY COST AUDIT IS IMPORTANT FOR A COMPANY',
  'category': 'Cost Audit',
  ' post_type': 'blog'},
 {'_id': '5e37dc1aeab55d319938a720',
  'title': 'WHAT IS STATUTORY AUDIT',
  'category': 'Auditing',
  ' post_type': 'blog'},
 {'_id': '5e37dc1aeab55d319938a720',
  'title': 'WHAT IS STATUTORY AUDIT',
  'category': 'Statuary Audit',
  ' post_type': 'blog'},
 {'_id': '5e3c7293eab55d319938a74d',
  'title': 'PHP',
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5e3c7293eab55d319938a74d',
  'title': 'PHP',
  'category': 'Programming languages',
  ' post_type': 'blog'},
 {'_id': '5e3fc856eab55d319938a7f2',
  'title': 'BASIC STRUCTURE DOCTRINE',
  'category': 'Legal Studies',
  ' post_type': 'blog'},
 {'_id': '5e3fc856eab55d319938a7f2',
  'title': 'BASIC STRUCTURE DOCTRINE',
  'category': 'Legal System',
  ' post_type': 'blog'},
 {'_id': '5e3fc931eab55d319938a7f4',
  'title': 'SPORTS LEGISLATIONS IN INDIA',
  'category': 'Sports Coaching',
  ' post_type': 'blog'},
 {'_id': '5e3fc931eab55d319938a7f4',
  'title': 'SPORTS LEGISLATIONS IN INDIA',
  'category': 'Sports Law',
  ' post_type': 'blog'},
 {'_id': '5e3fcb74eab55d319938a806',
  'title': 'Economics Sociology',
  'category': 'Economics',
  ' post_type': 'blog'},
 {'_id': '5e3fcb74eab55d319938a806',
  'title': 'Economics Sociology',
  'category': 'Economics Sociology',
  ' post_type': 'blog'},
 {'_id': '5e3fcc56eab55d319938a808',
  'title': 'Concept of Revenue',
  'category': 'Economics',
  ' post_type': 'blog'},
 {'_id': '5e3fcc56eab55d319938a808',
  'title': 'Concept of Revenue',
  'category': 'Revenue Concept',
  ' post_type': 'blog'},
 {'_id': '5e3fcd38eab55d319938a81a',
  'title': 'Human Rights and Duties',
  'category': 'Human Rights',
  ' post_type': 'blog'},
 {'_id': '5e3fcd38eab55d319938a81a',
  'title': 'Human Rights and Duties',
  'category': 'Rights and Duties',
  ' post_type': 'blog'},
 {'_id': '5e3fcfcdeab55d319938a81e',
  'title': 'Sociology of Religion',
  'category': 'Sociology',
  ' post_type': 'blog'},
 {'_id': '5e3fcfcdeab55d319938a81e',
  'title': 'Sociology of Religion',
  'category': 'Sociology of Religion',
  ' post_type': 'blog'},
 {'_id': '5e3fd10aeab55d319938a820',
  'title': 'Sociology in India',
  'category': 'Sociology',
  ' post_type': 'blog'},
 {'_id': '5e3fd10aeab55d319938a820',
  'title': 'Sociology in India',
  'category': 'Sociology in India',
  ' post_type': 'blog'},
 {'_id': '5e3fd290eab55d319938a822',
  'title': 'International Politics',
  'category': 'Political Science',
  ' post_type': 'blog'},
 {'_id': '5e3fd290eab55d319938a822',
  'title': 'International Politics',
  'category': 'International Politics',
  ' post_type': 'blog'},
 {'_id': '5e3fd3bdeab55d319938a824',
  'title': 'Colonialism in India',
  'category': 'Political Science',
  ' post_type': 'blog'},
 {'_id': '5e3fd3bdeab55d319938a824',
  'title': 'Colonialism in India',
  'category': 'Colonialism In India',
  ' post_type': 'blog'},
 {'_id': '5e3fd57aeab55d319938a826',
  'title': 'Labour law',
  'category': 'Legal Studies',
  ' post_type': 'blog'},
 {'_id': '5e3fd57aeab55d319938a826',
  'title': 'Labour law',
  'category': 'Labor Law',
  ' post_type': 'blog'},
 {'_id': '5e41b98eeab55d319938a82d',
  'title': 'PHP Variables',
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5e41b98eeab55d319938a82d',
  'title': 'PHP Variables',
  'category': 'Design and Analysis of Algorithms',
  ' post_type': 'blog'},
 {'_id': '5e41b98eeab55d319938a82d',
  'title': 'PHP Variables',
  'category': 'Programming languages',
  ' post_type': 'blog'},
 {'_id': '5e41bd7deab55d319938a839',
  'title': 'Operators In PHP',
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5e41bd7deab55d319938a839',
  'title': 'Operators In PHP',
  'category': 'Computer Application',
  ' post_type': 'blog'},
 {'_id': '5e41bd7deab55d319938a839',
  'title': 'Operators In PHP',
  'category': 'Programming languages',
  ' post_type': 'blog'},
 {'_id': '5e41bd7deab55d319938a839',
  'title': 'Operators In PHP',
  'category': 'Information Technology',
  ' post_type': 'blog'},
 {'_id': '5e431bf9eab55d319938a86a',
  'title': 'Computer Graphics',
  'category': 'Graphics',
  ' post_type': 'blog'},
 {'_id': '5e431bf9eab55d319938a86a',
  'title': 'Computer Graphics',
  'category': 'Computer Creation',
  ' post_type': 'blog'},
 {'_id': '5e45b5c9f5561b1994c8e32d',
  'title': 'EDI (Electronic data interchange)',
  'category': 'E Commerce',
  ' post_type': 'blog'},
 {'_id': '5e45b5c9f5561b1994c8e32d',
  'title': 'EDI (Electronic data interchange)',
  'category': 'Other Online Platforms',
  ' post_type': 'blog'},
 {'_id': '5e4a3cf6f5561b1994c8e378',
  'title': 'Making of the Joker sketch',
  'category': 'Drawing',
  ' post_type': 'skill'},
 {'_id': '5e4af475f5561b1994c8e385',
  'title': 'Lord shiva (Shadow Drawing)',
  'category': 'Drawings',
  ' post_type': 'artwork'},
 {'_id': '5e4af475f5561b1994c8e385',
  'title': 'Lord shiva (Shadow Drawing)',
  'category': 'Artistic design',
  ' post_type': 'artwork'},
 {'_id': '5e4ba3a9f5561b1994c8e392',
  'title': 'Hand Art',
  'category': 'Drawings',
  ' post_type': 'artwork'},
 {'_id': '5e4ba3a9f5561b1994c8e392',
  'title': 'Hand Art',
  'category': 'Artistic design',
  ' post_type': 'artwork'},
 {'_id': '5e4ba3a9f5561b1994c8e392',
  'title': 'Hand Art',
  'category': 'Illustration',
  ' post_type': 'artwork'},
 {'_id': '5e4c28c5f5561b1994c8e3b0',
  'title': 'E-Commerce - Business Models',
  'category': 'E Commerce',
  ' post_type': 'blog'},
 {'_id': '5e4c28c5f5561b1994c8e3b0',
  'title': 'E-Commerce - Business Models',
  'category': 'Shopping Platform',
  ' post_type': 'blog'},
 {'_id': '5e4c28c5f5561b1994c8e3b0',
  'title': 'E-Commerce - Business Models',
  'category': 'Other Online Platforms',
  ' post_type': 'blog'},
 {'_id': '5e4c3c09f5561b1994c8e3e6',
  'title': 'Stereoscopic and virtual-reality systems',
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5e4c3c09f5561b1994c8e3e6',
  'title': 'Stereoscopic and virtual-reality systems',
  'category': 'Hardware',
  ' post_type': 'blog'},
 {'_id': '5e4c3c09f5561b1994c8e3e6',
  'title': 'Stereoscopic and virtual-reality systems',
  'category': 'Information Technology',
  ' post_type': 'blog'},
 {'_id': '5e4c3d1df5561b1994c8e3f3',
  'title': 'Raster graphics systems',
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5e4c3d1df5561b1994c8e3f3',
  'title': 'Raster graphics systems',
  'category': 'Computation',
  ' post_type': 'blog'},
 {'_id': '5e4c3d1df5561b1994c8e3f3',
  'title': 'Raster graphics systems',
  'category': 'Computer Application',
  ' post_type': 'blog'},
 {'_id': '5e4d359cf5561b1994c8e424',
  'title': 'Business skills',
  'category': 'Business',
  ' post_type': 'blog'},
 {'_id': '5e4d359cf5561b1994c8e424',
  'title': 'Business skills',
  'category': 'Business Skills',
  ' post_type': 'blog'},
 {'_id': '5e50141ed15de17a8cf1b912',
  'title': 'Firewall',
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5e50141ed15de17a8cf1b912',
  'title': 'Firewall',
  'category': 'Computer Application',
  ' post_type': 'blog'},
 {'_id': '5e50141ed15de17a8cf1b912',
  'title': 'Firewall',
  'category': 'Hardware',
  ' post_type': 'blog'},
 {'_id': '5e50141ed15de17a8cf1b912',
  'title': 'Firewall',
  'category': 'Information Technology',
  ' post_type': 'blog'},
 {'_id': '5e501d55d15de17a8cf1b91f',
  'title': 'DATA AND MESSAGE SECURITY',
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5e501d55d15de17a8cf1b91f',
  'title': 'DATA AND MESSAGE SECURITY',
  'category': 'Computer Application',
  ' post_type': 'blog'},
 {'_id': '5e50207cd15de17a8cf1b92c',
  'title': 'Mobile Computing Technology',
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5e50207cd15de17a8cf1b92c',
  'title': 'Mobile Computing Technology',
  'category': 'Mobile Applications',
  ' post_type': 'blog'},
 {'_id': '5e502673d15de17a8cf1b946',
  'title': 'Data Transmission Modes',
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5e502673d15de17a8cf1b946',
  'title': 'Data Transmission Modes',
  'category': 'Computer Application',
  ' post_type': 'blog'},
 {'_id': '5e502673d15de17a8cf1b946',
  'title': 'Data Transmission Modes',
  'category': 'Operating Systems',
  ' post_type': 'blog'},
 {'_id': '5e518c9fd701ab08af79299a',
  'title': "Topology & it's types",
  'category': 'Computer Technology',
  ' post_type': 'blog'},
 {'_id': '5e518c9fd701ab08af79299a',
  'title': "Topology & it's types",
  'category': 'Information Technology',
  ' post_type': 'blog'},
 {'_id': '5e518c9fd701ab08af79299a',

In [47]:
update_data = (
    post
    .assign(category=post['category'].str.split('|'))
    .explode('category')                              
    .reset_index(drop=True)                          
)

In [48]:
update_data

,_id,title,category,post_type
0,5d62abaa65218653a132c956,hello there,Plant Biotechnology,blog
1,5d6d39567fa40e1417a4931c,Ml and AI,Artificial Intelligence,blog
2,5d6d39567fa40e1417a4931c,Ml and AI,Machine Learning,blog
3,5d6d39567fa40e1417a4931c,Ml and AI,Information Technology,blog
4,5d7d23315720533e15c3b1ee,What is an Operating System ?,Operating Systems,blog
...,...,...,...,...
925,5ed3ef4cbd514d602c1530f2,Recommendation Engine,random,project
926,5ed415c6bd514d602c15312d,Face Recognition using Transfer Learning.,Science; Technology,skill
927,5ed4cbadbd514d602c1531a6,Configure CI/CD Pipeline in GitLab and deploym...,Computer Technology,blog
928,5ed4cbadbd514d602c1531a6,Configure CI/CD Pipeline in GitLab and deploym...,Computer Application,blog
929,5ed4cbadbd514d602c1531a6,Configure CI/CD Pipeline in GitLab and deploym...,Information Technology,blog

In [51]:
post1 = pd.DataFrame(update_data)
post1

,_id,title,category,post_type
0,5d62abaa65218653a132c956,hello there,Plant Biotechnology,blog
1,5d6d39567fa40e1417a4931c,Ml and AI,Artificial Intelligence,blog
2,5d6d39567fa40e1417a4931c,Ml and AI,Machine Learning,blog
3,5d6d39567fa40e1417a4931c,Ml and AI,Information Technology,blog
4,5d7d23315720533e15c3b1ee,What is an Operating System ?,Operating Systems,blog
...,...,...,...,...
587,5ed23c8676027d35905cc780,Change.,Calligraphy,artwork
588,5ed23c8676027d35905cc780,Change.,Pen and ink,artwork
589,5ed23e4d76027d35905cc7b8,Success Story Of OYO Founder Ritesh Agarwal,Mass Media,blog
590,5ed23e4d76027d35905cc7b8,Success Story Of OYO Founder Ritesh Agarwal,Media And Society,blog
591,5ed415c6bd514d602c15312d,Face Recognition using Transfer Learning.,Science; Technology,skill

In [56]:
post1['category'].unique()

array(['Plant Biotechnology', 'Artificial Intelligence',
       'Machine Learning', 'Information Technology', 'Operating Systems',
       'Drawings', 'Competition Laws', 'Eco System', 'Economic Policies',
       'Graphic', 'Graphic Design', 'Painting', 'Pen and ink',
       'Computer Technology', 'Visual Arts', 'Illustration',
       'Calligraphy', 'Photography', 'Empowerment', 'random',
       'Video editing', 'Inorganic Chemistry', 'Programming languages',
       'Conceptual', 'HR Management', 'Human Resources', 'Mass Media',
       'International Relations', 'Sculptures', 'Artistic design',
       'Fashion Design', 'Ceramics', 'Craft', 'Mathematics',
       'Linear Algebra', 'Electronics & electrical Technology',
       'Electrical Machines', 'Auditing', 'Internal Audit', 'E Commerce',
       'E Transactions', 'Computation', 'Internal Financial Control',
       'Taxation', 'Custom Laws', 'Audit Evidence', 'GST', 'Direct Tax',
       'Secratarial Audit', 'Banking', 'Banking Companies',
       'Banking Technology', 'Audit Remark', 'Cost Audit',
       'Statuary Audit', 'Legal Studies', 'Legal System',
       'Sports Coaching', 'Sports Law', 'Economics',
       'Economics Sociology', 'Revenue Concept', 'Human Rights',
       'Rights and Duties', 'Sociology', 'Sociology of Religion',
       'Sociology in India', 'Political Science',
       'International Politics', 'Colonialism In India', 'Labor Law',
       'Design and Analysis of Algorithms', 'Computer Application',
       'Graphics', 'Computer Creation', 'Other Online Platforms',
       'Drawing', 'Shopping Platform', 'Hardware', 'Business',
       'Business Skills', 'Mobile Applications', 'Communication',
       'Basics of Communiaction', 'Prints', 'Marketing', 'Advertising',
       'Political Thought', 'Accounting', 'Fundamental Of Accounting',
       'Mixed Media', 'Management', 'Team Mangememnt',
       'Corporate Social Responsibilities', 'Philosophy',
       'Applied Ethics', 'Performance In Organization',
       'Organizational Behaviour', 'Fashion Desigining',
       'Fashion Textile', 'Fashion Manufacturing', 'Fashion Techniques',
       'Garment Production', 'Garment Technology',
       'Promotion And Distribution Decisions', 'Biotechnology',
       'Genetic Engineering', 'Physiology', 'Neurology',
       'Indian Government', 'Osteology', 'Cardiology', 'Zoology',
       'Ecology', 'Cloud Computing', 'Radiology', 'Molecular Biology',
       'Gastroenterology', 'Logic', 'Watercolours', 'Tapestry',
       'Robotics', 'Data Science', 'Public Philosophy',
       'Digital Marketing', 'Videography', 'Acrylics', 'Sports Event',
       'Government and Politics', 'Geography', 'Physical Geography',
       'Education', 'Business Organisation', 'Environmental Biology',
       'Fundamental Rights', 'Marketing Management',
       'Partnership Accounting', 'Corporate Accounting',
       'Accounting Theory And Practices', 'Income Tax Laws',
       'Articulation', 'Archeology', 'Human Prehistory', 'Start Ups',
       'Entreperneurship', 'Business Strategies', 'Venture Capitalist',
       'Business Planning', 'Indian Geography', 'Digital India',
       'Bio-entrepreneurship', 'Literature', 'Stories', 'History',
       'Indian History', 'ViDEO', 'Business Management', 'Social Work',
       'Health Education', 'Social Tech', 'Humanities',
       'Financial Accounting', 'Psycholgy', 'Social Psychology',
       'Physics', 'Instrumentation', 'Craft work', 'Social Interventions',
       'Substance Abuse', 'Indian Economy', 'Finance',
       'Financial Analysis', 'Architecture', 'Web designing',
       'Database Management', 'Movements in Literature', 'Atomic Physics',
       'Energy Physics', 'Quantum Mecahnics', 'Protection & Enforcement',
       'Environment Studies', 'Pollution', 'Industrial Instrumentation',
       'Nuclear & Particle Physics', 'Environmental Biotechnology',
       'Alternate Dispute Resolution', 'International Treaties',
       'International Agreement', 'Principles Of Marketing',
       'Marketing Research Methadology', 'International Marketing',
       'Child Development', 'Break even Point', 'Foreign Economy',
       'Psychological Growth', 'Technology Mangement',
       'Managerial Activity', 'Creative And Lateral Management',
       'Business Enviorment', 'New Venture Planning', 'Foreign Business',
       'NGO', 'Fine Arts', 'Legal Tradition', 'Nationality Law',
       'Government Law', 'Company Law', 'Banking Law',
       'Frontend Development', 'Music', 'Wood Crafts', 'Wood carving',
       '2D Composition', 'Mosaic painting', 'Video',
       'Fashion Illustration', 'Pattern Cutting', 'Fashion Communication',
       'Animal Biotechnology', 'Pattern & Culture', 'Fashion Trends',
       'Fashion Portfoilio', 'Sketch Video', 'Test', 'Professionalism',
       'Art', 'Science;Technology', 'Art; Science', 'Logo Design',
       'Learning', 'Fictions', 'Technology', 'Typography',
       'Media And Society', 'Science; Technology'], dtype=object)

In [57]:
view.columns

Index(['user_id', 'post_id', 'timestamp'], dtype='object')

In [58]:
post1.columns

Index(['_id', 'title', 'category', ' post_type'], dtype='object')

In [59]:
user.columns

Index(['_id', 'name', 'gender', 'academics'], dtype='object')

In [61]:
post1.rename(columns={'_id':'post_id'}, inplace=True)
user.rename(columns={'_id':'user_id'}, inplace=True)

In [62]:
user.columns

Index(['user_id', 'name', 'gender', 'academics'], dtype='object')

In [63]:
post1.columns

Index(['post_id', 'title', 'category', ' post_type'], dtype='object')

In [64]:
main = pd.merge(view, post1, on='post_id', how = 'inner')

In [65]:
main

,user_id,post_id,timestamp,title,category,post_type
0,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z,Save Earth.,Visual Arts,artwork
1,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z,Save Earth.,Graphic Design,artwork
2,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z,Save Earth.,Artistic design,artwork
3,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z,Save Earth.,Graphic,artwork
4,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z,Save Earth.,Illustration,artwork
...,...,...,...,...,...,...
1747,5d60098a653a331687083238,5e7a629ccfc8b713f5ac7d84,2020-03-26T19:01:42.384Z,3D composition.,Tapestry,artwork
1748,5d60098a653a331687083238,5e7cc074cfc8b713f5ac7db0,2020-03-26T18:49:14.721Z,REAL TALK,Philosophy,blog
1749,5d60098a653a331687083238,5e7cc074cfc8b713f5ac7db0,2020-03-26T18:49:14.721Z,REAL TALK,Public Philosophy,blog
1750,5d60098a653a331687083238,5e1029f22a37d20505da2a79,2020-03-26T18:25:45.637Z,Chat App UI Desgin,Conceptual,artwork
1751,5d60098a653a331687083238,5e1029f22a37d20505da2a79,2020-03-26T18:25:45.637Z,Chat App UI Desgin,Graphic Design,artwork

In [66]:
main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1752 entries, 0 to 1751
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     1752 non-null   object
 1   post_id     1752 non-null   object
 2   timestamp   1752 non-null   object
 3   title       1752 non-null   object
 4   category    1752 non-null   object
 5    post_type  1752 non-null   object
dtypes: object(6)
memory usage: 82.3+ KB

In [67]:
main.describe()

,user_id,post_id,timestamp,title,category,post_type
count,1752,1752,1752,1752,1752,1752
unique,88,232,628,228,235,4
top,5d60098a653a331687083238,5ec7abfdec493f4a26558860,2020-05-25T07:27:20.699Z,FASHION ILLUSTRATION (OP ART),Illustration,blog
freq,262,63,7,63,78,846

### Создание матрицы пользователи-категории

In [68]:
users = list(main['user_id'].unique())
categories = list(main['category'].unique())

In [72]:
print(len(users))
print(len(categories))

88
235

In [73]:
user_mat = [[] for i in range(len(users))]
for i in range(len(users)):
    for j in range(len(categories)):
        value = len(main[(main['user_id'] == users[i]) & (main['category'] == categories[j])])
        user_mat[i].append(value)

In [77]:
for i in user_mat[67]:
    print(i, end = ' ')

2 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [78]:
from scipy.sparse import csr_matrix
user_mat = csr_matrix(user_mat)

In [79]:
user_mat

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1036 stored elements and shape (88, 235)>

In [80]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=15)

In [81]:
model.fit(user_mat)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=15)

In [92]:
def recommender(user_id, data=user_mat, model=model):
    model.fit(data)
    index = users.index(user_id)
    current_user = main[main['user_id'] == user_id]
    dist, indices = model.kneighbors(data[index], 10)
    recommendation = []
    for i in indices[0]:
        user = main[main['user_id'] == users[i]]
        for j in user['category'].unique():
            if i not in current_user['category'].unique() and j not in recommendation:
                recommendation.append(j)
    return recommendation

In [93]:
recommender(users[7])[:10]

['Mixed Media',
 'Marketing',
 'Advertising',
 'Promotion And Distribution Decisions',
 'Digital Marketing',
 'Business',
 'Geography',
 'Indian Geography',
 'Business Organisation',
 'Principles Of Marketing']