In [104]:
!pip install yfinance
!pip install pandas_datareader

Requirement already satisfied: yfinance in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (2.3.1)
Requirement already satisfied: numpy>=1.16.5 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (2.3.2)
Requirement already satisfied: requests>=2.31 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (4.2.2)
Requirement already satisfied: pytz>=2022.5 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (3.18.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (6.32.1)
Requirement already satisfied: websockets>=13.0 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.12.2)
Requirement already satisfied: cffi>=1.12.0 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from curl_cffi>=0.7->yfinance) (2025.8.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2.9.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.22)
Requirement already satisfied: six>=1.5 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Requirement already satisfied: pandas_datareader in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (0.10.0)
Requirement already satisfied: lxml in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from pandas_datareader) (6.0.2)
Requirement already satisfied: pandas>=0.23 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from pandas_datareader) (2.3.1)
Requirement already satisfied: requests>=2.19.0 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from pandas_datareader) (2.32.5)
Requirement already satisfied: numpy>=1.23.2 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from pandas>=0.23->pandas_datareader) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from pandas>=0.23->pandas_datareader) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from requests>=2.19.0->pandas_datareader) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from requests>=2.19.0->pandas_datareader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from requests>=2.19.0->pandas_datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from requests>=2.19.0->pandas_datareader) (2025.8.3)
Requirement already satisfied: six>=1.5 in /Users/artemgolubnichiy/myJupyterNotebook/.conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.16.0)

In [105]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pandas_datareader.data import DataReader
import yfinance as yf
from pandas_datareader import data as pdr

# yf.pdr_override()

In [106]:
from datetime import datetime

tech_list = ['AAPL', 'GOOG', 'MSFT', 'AMZN']
end = datetime.now()
start = datetime(end.year - 2, end.month, end.day)

In [107]:
for stock in tech_list:
    globals()[stock] = yf.download(stock, start, end)

/var/folders/24/z61d72zx27z5ml8twybhwmm40000gn/T/ipykernel_96973/2406771750.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  globals()[stock] = yf.download(stock, start, end)
[*********************100%***********************]  1 of 1 completed
/var/folders/24/z61d72zx27z5ml8twybhwmm40000gn/T/ipykernel_96973/2406771750.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  globals()[stock] = yf.download(stock, start, end)
[*********************100%***********************]  1 of 1 completed
/var/folders/24/z61d72zx27z5ml8twybhwmm40000gn/T/ipykernel_96973/2406771750.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  globals()[stock] = yf.download(stock, start, end)
[*********************100%***********************]  1 of 1 completed
/var/folders/24/z61d72zx27z5ml8twybhwmm40000gn/T/ipykernel_96973/2406771750.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  globals()[stock] = yf.download(stock, start, end)
[*********************100%***********************]  1 of 1 completed

In [108]:
AAPL.columns = AAPL.columns.droplevel(1)
GOOG.columns = GOOG.columns.droplevel(1)
MSFT.columns = MSFT.columns.droplevel(1)
AMZN.columns = AMZN.columns.droplevel(1)

In [109]:
AAPL

Price            Close        High         Low        Open     Volume
Date
2023-09-22  173.094543  175.362339  172.361731  172.975712   56725400
2023-09-25  174.372040  175.253406  172.460753  172.510271   46172700
2023-09-26  170.291992  173.500554  169.994899  173.124251   64588900
2023-09-27  168.776825  171.361509  167.410221  170.945584   66921800
2023-09-28  169.034332  170.361331  165.994104  167.697421   56294400
...                ...         ...         ...         ...        ...
2025-09-15  236.699997  238.190002  235.029999  237.000000   42699500
2025-09-16  238.149994  241.220001  236.320007  237.179993   63421100
2025-09-17  238.990005  240.100006  237.729996  238.970001   46508000
2025-09-18  237.880005  241.199997  236.649994  239.970001   44249600
2025-09-19  245.500000  246.300003  240.210007  241.229996  163470300

[500 rows x 5 columns]

In [110]:
company_list = [AAPL, GOOG, MSFT, AMZN]
company_name = ['APPLE', 'GOOGLE', 'MICROSOFT', 'AMAZON']

In [111]:
for company, com_name in zip(company_list, company_name):
    company['company_name'] = com_name

In [112]:
df = pd.concat(company_list, axis=0)

In [115]:
df.head()

Price            Close        High  ...    Volume  company_name
Date                                ...
2023-09-22  173.094543  175.362339  ...  56725400         APPLE
2023-09-25  174.372040  175.253406  ...  46172700         APPLE
2023-09-26  170.291992  173.500554  ...  64588900         APPLE
2023-09-27  168.776825  171.361509  ...  66921800         APPLE
2023-09-28  169.034332  170.361331  ...  56294400         APPLE

[5 rows x 6 columns]