In [87]:
import pandas as pd
import numpy as np

In [88]:
df = pd.read_csv('Restaurant reviews.csv')
print(df.shape)

(10000, 8)

In [89]:
df.head()

,Restaurant,Reviewer,Review,Rating,Metadata,Time,Pictures,7514
0,Beyond Flavours,Rusha Chakraborty,"The ambience was good, food was quite good . h...",5,"1 Review , 2 Followers",5/25/2019 15:54,0,2447.0
1,Beyond Flavours,Anusha Tirumalaneedi,Ambience is too good for a pleasant evening. S...,5,"3 Reviews , 2 Followers",5/25/2019 14:20,0,NaN
2,Beyond Flavours,Ashok Shekhawat,A must try.. great food great ambience. Thnx f...,5,"2 Reviews , 3 Followers",5/24/2019 22:54,0,NaN
3,Beyond Flavours,Swapnil Sarkar,Soumen das and Arun was a great guy. Only beca...,5,"1 Review , 1 Follower",5/24/2019 22:11,0,NaN
4,Beyond Flavours,Dileep,Food is good.we ordered Kodi drumsticks and ba...,5,"3 Reviews , 2 Followers",5/24/2019 21:37,0,NaN

In [90]:
df = df.drop(['Restaurant', 'Reviewer', 'Metadata', 'Time', 'Pictures', '7514'], axis=1)
df.head()

                                              Review Rating
0  The ambience was good, food was quite good . h...      5
1  Ambience is too good for a pleasant evening. S...      5
2  A must try.. great food great ambience. Thnx f...      5
3  Soumen das and Arun was a great guy. Only beca...      5
4  Food is good.we ordered Kodi drumsticks and ba...      5

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  9955 non-null   object
 1   Rating  9962 non-null   object
dtypes: object(2)
memory usage: 156.4+ KB

In [92]:
df['Rating'].unique()

array(['5', '4', '1', '3', '2', '3.5', '4.5', '2.5', '1.5', 'Like', nan],
      dtype=object)

In [93]:
df['Rating'].isna().sum()

np.int64(38)

In [94]:
df['Rating'].value_counts()

Rating
5       3832
4       2373
1       1735
3       1193
2        684
4.5       69
3.5       47
2.5       19
1.5        9
Like       1
Name: count, dtype: int64

In [95]:
df['Rating'] = np.where(df['Rating'] == 'Like', df['Rating'].value_counts().idxmax(), df['Rating'])

In [96]:
df['Rating'].unique()

array(['5', '4', '1', '3', '2', '3.5', '4.5', '2.5', '1.5', nan],
      dtype=object)

In [97]:
df['Rating'] = list(map(lambda data: float(data)>=3, df['Rating']))
df['Rating'].unique()

array([ True, False])

In [98]:
df.head()

                                              Review  Rating
0  The ambience was good, food was quite good . h...    True
1  Ambience is too good for a pleasant evening. S...    True
2  A must try.. great food great ambience. Thnx f...    True
3  Soumen das and Arun was a great guy. Only beca...    True
4  Food is good.we ordered Kodi drumsticks and ba...    True

In [99]:
df['Review'].isnull().sum()

np.int64(45)

In [100]:
df['Review'] = df['Review'].fillna('Nothing')
df['Review'].isnull().sum()

np.int64(0)

### Обработка естественного языка

In [101]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import re

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [102]:
ps = PorterStemmer()

In [103]:
reviewList = list(map(lambda data: word_tokenize(data), df['Review']))

In [104]:
for index, word_list in enumerate(reviewList):
    reviewList[index] = ' '.join([ps.stem(str(word)) for word in word_list if not word in stopwords.words('english') and word not in ['.', ',', '?', '@', '$', '/'] and not word.isspace()])

In [105]:
reviewList

['the ambienc good food quit good saturday lunch cost effect good place sate brunch one also chill friend parent waiter soumen da realli courteou help',
 'ambienc good pleasant even servic prompt food good over good experi soumen da - kudo servic',
 'a must tri .. great food great ambienc thnx servic pradeep subroto my person recommend penn alfredo pasta : ) ....... also music background amaz',
 'soumen da arun great guy onli behavior sincereti and good food cours i would like visit place',
 'food good.w order kodi drumstick basket mutton biryani all good thank pradeep he serv well we enjoy ambienc also good',
 'ambianc good servic good food apradeecp subro best servic food good papiya good hostess ur caption good thi 4star restaur',
 'it nice place ambienc differ food order tasti servic also gud worth visit it reason well realli must visit place',
 'well read mani review final visit place ... ambienc good come food crispi corn nice tawa fish ok ... basket biryani disappoint us ... biryani ok flatter claim .. staff polit prompt especi pradeep suman',
 'excel food special like spici food courteou staff shubro pradeep papiya gave excel servic corpor team dinner overal great team dinner parti',
 'came birthday treat close friend perfect place treat like veri hospit cooper staff food delici ambienc realli good music light chili honey lotu stem must tri special mention papiya took good care us',
 'the servic great food awesom the servic staff manab papiya courteou attent i would like come frequent place',
 'veri good ambienc amaz food good servic friendli staff - pradeep papiya shuvro : ) definit visit ! and love design menu card',
 'food good soup expect in starter order honey chilli lotu stem must tri vegan ppl servic great frequent visit papiya know experi also food realli impress',
 'food good telangana kodiak fri must try.mutton biriyani good.papiya help choos best dish attend well.must visit',
 'we order corn chees ball manchow soup paneer shashlik sizzler the sizzler stale paneer smell waiter impolit even accept mistak never go',
 'food ambienc fantast .. waiter manav maji realli quick servic .. chees ball must tri starter scrumptiou',
 'came lunch food good tasti we tri buffet item veg non-veg tasti the ambienc servic also good staff courteou shubhamtraveltales.wordpress.com',
 "the best thing place food my favorit go dish definit alfredo pasta although item good well and servic behavior staff top-notch we 're attend mr. soumen da extrem polit will definit visit soon",
 'polit friendli staff nice ambienc good spread menu drink awesom servic good manav ... look forward see ...',
 'food realli good we vegetarian item includ paneer mushroom kofta addit servic papiya shuvro realli good',
 "beauti cozi classi time place truli recommend special day with 15 percent corpor discount treat cotori well without burn hole ur pocket also interior done well love vibe on menu honey chilli lotu stem basket biryani sizzl browni favourit also love tomato basil shorba differ creami standard restaur i 'm definit make visit beyond flavour special mention papiya hostess even excel servic : )",
 'pleas good quit expens come tast rate 3 5 cant click better pictur wen visit night🤣🤭best day time pic',
 'servic good fast even peopl polit well behav manav pradeep good hope everyon behav way',
 'we farewel feast recent enjoy well good manag boy gave complimentari food made us happi food perfect dessert starter wonder',
 'excel experi mouthwat food good ambienc must go place hyderabad we serv shubhro papiya they awesom behaviour had enjoy even friend',
 'the place good .. 5 * live music .. she superb beauti voic .. food nice n love lightn .. 😍entranc also nice ..',
 'sonalin great voic .. 😍 must visit place .. becam fan the food good .. 5 star side live music lighten everyth awesom 😍',
 'i heard voic .. beauti amaz voic .. love voic way sing 😍 becam fan sonalin priyadarshini good place must visit the food also nice ..',
 'sonalin good singer citi .. beauti face beauti face must visit place .. beauti live music .. love .. 😍 love food well veri good lightn',
 'food descent enough desert option also good starrer also tasti one bad experi ee wait time even though book tabl prior time',
 "short review : decent bread starter bad shaam savera littl screw daal makhni ( one-off case ) better ambienc night ... and importantli good quantiti ! i want give 2.5 's option 🙈 extens ... ambienc : it 's better night friend day n't like much so prefer ambienc go night ! food ! order hara bhara kebab shaam savera daal makhni roti raita ( ye ! i 'm vegetarian 🙈 ) the good part ! quantiti 😍 i excit see shaam savera menu but take want order it close they mess real bad especi color the daal makhni big chunk garlic clove spoil it n't creami : ( the bread raita decent ! the hara bhara kebab decent soft ! they extra outer coat peanut so 're peanut fan kebab ask skip step 🙈 conclus : it look like made food hurri would like give place anoth tri hope mine one odd case if thing chang 'll know !",
 'excel food good servic soumen da .. ambienc good live music food serv time decor restaur amaz well',
 "my review place would 5star ambeinc servic staff lack lot 's place even though food good place like special hey papiya shuvro !",
 'it nice experi food amaz friendli staff welcom attitud papia friendli accommod good ambianc i definit recommend place',
 'had dinner friend menu perfect someth everyon servic awesom papia accommod good ambienc amaz live music will back definit !',
 'servic experi good especi papiya food serv good tasti serv well i would like visit beyond recommend friend food reason price',
 'servic food ambianc nice staff humbl take order serv food live music like cherri cake',
 'the food ❤️ .. we order banjara tangdi starter best among .. papiya shuvro well manner servic best among',
 'staff polit respons food best part and better ambienc also awesom i met two person name papiya shuvro best servic food item like basket biryani kodi drum stick final love',
 'i came parent we order thai peneer tikka kaju pulao veg biryani the kaju pulao veg biryani realli good thi decent place go famili shubro papiya serv well',
 'well ’ new hyderabad and i fact say ’ probabl best place i ’ eaten buffet hyderabad period especi id like thank shurvo papiya amaz servic doubl metha good overal worthwhil experi',
 'wonder place awesom ambienc best visit night see pretti light enjoy savori food shubro papiya good servic',
 "good ambienc great service.w 've buffet 25 people.th waiter patient even got noodl replac sinc one serv buffet went bad shoutout shubro pradeep took care entir afternoon",
 "my review place come multipl visit span 4 month and i safe say 's one good place around they 're locat near biodivers signal fabindia there 's ampl park two four wheeler the ambienc bit dim dark seat divid variou option includ pdr section the menu design shape bottl array span continent chines indian cuisin here 's list thing i tri across visit panko crumb mozzarella stick ❤️ - chees stick coat fri pure chees bliss veg lasagna ❤️ - thi place one good lasagn town crispi chilli corn kernel - the usual favourit one slightli differ present makhmali paneer tikka - cottag chees shashlik sizzler italian nacho - nacho top red sauc chees bake dish chees chees pizza ❤️ - soft base pizza load chees piec green oliv i stress enough i love i tri i also tri lunch buffet the varieti may elabor place food qualiti discount offer bulk book least one-tim tri but i realli ador mocktail beyond delight absolut delight ! also fan guava chilli appl kiwi night drink the staff ever courteou a special mention papiya shuvro attend latest visit the place zomato gold 1+1 bring reason rate a meal two would roughli around 700 fill tummi also heart !",
 'had lunch today beyond flavor .the food good delici awesom servic provid soumen da & shuvro would highli recommend restaur',
 "the reason give 3 star longlong time wait tabl we went friday afternoon we wait almost 30min get tabl we lost patienc left anoth restaur v n't get tabl even aftr wait long time.i think restaur manag take consider tri decreas wait time custom",
 'servic realli except cheer manav serv us realli well food nice love ambienc nice music play background',
 'soumen da wait tabl ! thank buddi great servic will visit soon ! soumen da wait tabl ! thank buddi great servic will visit soon ! soumen da wait tabl ! thank buddi great servic will visit soon ! soumen da wait tabl ! thank buddi great servic will visit soon !',
 'papiya shuvro great she help us get tabl quickli suggest us best sizzler menu ambienc awesom she suggest best tabl help till will visit awesom servic you guy tri well u plan take love one n give osm experi place',
 'quit good ambienc like special restro biryani must tri like servic papiya shuvro realli good der service.wil like visit again.it nice place visit special nyt tym.food yum.should tri biryani',
 'pradeep shubroto amaz friendli servic awesom n food world.must visit peopl will visit',
 'we visit place colleagu farewel we realli great time.good food servic pradeep shobro will come later',
 'the restaur amaz ambienc staff polit suggest good recommend food if visit beyond flavour sometim reach papiya shuvro suggest realli good dish',
 'excel food servic special mention papiya shuvro surpris see good qualiti food serv low price ambienc quit good highli recommend',
 'papiya shuvro f & b execut realli courteou friendli thoroughli enjoy experi good place cute lil date hehe nice famili dinner',
 'thi first time visit restaur experi good term food hospit servic ambienc thank shubro papiya hospit',
 "we went lunch buffet yesterday took chanc see good averag review zomato the spread buffet less 3 veg 3 non veg starter 2 main cours veg non veg one fri rice chicken biryani dessert ice cream jamun the tast ok expect much littl disappoint starter hot fish fri decent schezwan chicken ok. veg spring roll good big surpris onion ring starter 🤣😂 kadai ghost main cours good miss masala flavour chicken ok. biryani averag egg fri rice good for money pay expect good food they use much colour food item 's suggest manag use less coat less food colour starter overal experi ok much better amount pay",
 'the place beyond beauti ambienc excel food good the servic soumen da extrem good highli recommend place',
 'i beyond time tri lot dish never disappoint i would special recommend soup healthi broth soup roast chicken soup amaz in addit servic great server papiya courteou prompt thi place becom go place good dine experi',
 'if time wast tast u r welcom ... tast realli superb servic slow .. ! dish impress differ flavour like .. !',
 'the food good would add could increas spread.ananya courteou good serv .. ! ! ambienc also good peac ........................... ! ! ! ! ! ! ! ! ! ! ♥️♥️♥️♥️♥️♥️♥️♥️♥️',
 'pardeep shubrat serv great food great ambienc must tri ! ! ! the food awesom ambienc good a great place go team',
 'one best restaur hyderabad near gachibowli .. ambianc good .. lunch spread good tasti thank papiya guidanc',
 'i realli like food differ get everi restaur .. realli appreci servic papiya .. love present food ..',
 'had good food good time place .. ambienc realli good nice time ... thank shubro assist guidanc food ..',
 'best place hangout ... 😊 food realli great ... thank papiya servic ... 😊 staff reallli co-op ... ambienc realli great especi pdr ( privat dine room ) awesom ... 😍👌🏻',
 'went team lunch worst restaur .. food tasteless servic slow ac work we ’ request multipl time use pleas ’ wast money i strictli recommend prefer beyond flavour',
 "discov place return despic day offic walk order food think 'd takeout food one could get outlet but but food turn saviour and way 've design place inde remark the light mix setup would give retro feel good normal group peopl would want sit great convers food",
 "second time 's realli beyond imagin beyond tast beyond flavour well veri courteou staff hospitil tast good best part present 's realli meet standard 5 star restaur veri impress mr ahm pradeep mr dipanajan friendli took care us well good job guy keep",
 'we order veget lasagn sizzler chicken tikka absolut delici the ambienc amaz servic good',
 'one best food experi i hyderabad the dessert yum appricot pud must ahm khan servic unparal keep good work',
 'ahm great help beyond flavour ... he may suggest great food good experi the stater sizzler good the sauc use chicken dish awsom nan soft even take without butter easili eat great experi beyond flavor',
 'had dinner place attend papiya the staff friendli ambianc awesom good varieti food beverag',
 'we happen go place last sunday mother day flat 50 buffet meal mother realli like .. needless say ambienc music realli good .we reserv wait fir 10 min get seat .. they serv us mango juic wrlcome drink tast realli good.th buffet spread one kind : strter : veg : paneer tikka veg spring roll veg cutlet.they lil cold tast wad good non veg : chicken kebab chicken manchurian fish .fish tasti though coupd tast better hot.chicken fair enuf singapor noodl egg salad pasta : they good cold main cours : mutton rogan josh chicken tikka masala palak paneer all equal good biriyani : egg fru rice chicken biriyani realli great dessert : moong dal halwa tast realli yumm ice cream gulab jamun cut fruit banana cake the staff slow servic food refil slow.w wait quit long time actual eat stomach full they could improv point stand better ! overal :3.2',
 'good ambienc absolut delici food i ’ got best compani ananya ( beyond flavour ) the place quit peac music fun love staff great place friend',
 'i place dinner day back the ambienc good the restaur almost half occupi we immedi got tabl but wait 10 min get water menu remind we order starter main cours item mock drink onli starter could serv 30 min there sign mock drink ! we notic similar servic issu tabl notic guest liter shout staff the food averag dish prepar well least compar 4.1 rate zomato we final decid starter hop onto anoth restaur rest meal !',
 "i place twice 2 differ experi 1st time colleagu i love food ambienc servic everyth except price costli their special bake biriyani work tri 's uniqu tasti becaus good experi i revisit place sister she order mocktail terrible.they replac still good and i ask starter bone boneless told boneless later arriv told come it 's disappoint know staff n't know menu",
 "it 's one best place hangout friend seem like quiet common place group lunch etc food good ambienc also nice love everything.❤",
 'ambienc good staff polit friendli food super good nice time lunch .... keep good work thank nice hospit love 💕 💕 💕',
 "i would like introduc restaur new ingredi call salt if add yo food would tast way better so basic none food order salt we order fri panko mozzarella stick tomato cream soup panner65 & `` italian '' nacho not sure nacho italian they basic bought pack doritto ad mozarella chees top the bean bake entir dish cold except plate brought pretti sure dump item stash insid microwav the paneer 65 horrend might well call garlic 65 salt next mozarella stick cold salt the decent item got fri soup thank gid didnt order main cours all came 1300 odd thank zomato gold price went thi place way expens qualiti food serv and talk restaur gener place look decent stove stash tabl seat plant kept inconveni spot they realli need clean",
 "hostil staff okeish food great ambianc not sure rate zomato stand 4.1 starter 're decent main cours horribl will suggest place",
 'thank ahm food great recommend visit servic excel ambienc good great time famili',
 'thi place flavor food servic like beyond good beyond expect realli realli qualiti worth money.i person highli recommend place.great flavour food much prompt service.ambi also enhanc flavor restaur',
 'food qualiti tast good super slow servic nice ambienc poor custom handl lot item avail even menu',
 'thi worst experi restaur ever first starter serv half hour order chicken popcorn hair strand yuck ! then guy took main cours order forgot complet order wait almost hour then wait anoth half hour get food and worst got us chicken lasagna instead veg lasagna we figur chicken right one staunch vegetarian friend almost ate i recommend place there mani better place gachibowli could save time provid better servic',
 'thi place i realli recommend restaur food lover specif continent food lover.pasta sizzler yummi i cant stop choos restaur rather other.servic part realli satisfi',
 "i 'm much impress qualiti food servic special mr ahm thank polit readi about food say beyond flavour love place must visit great ambienc",
 'the food inde beyond falvour ahm serv us well hope meet next time soon a great ambienc amaz song background ad innumer flavour delici food',
 'starter good servic also good ahm polit help us select menu.l tune great would like come back',
 'had bad experi beyond flavour realli put beyond flavour gone dinner next day get hospitalis food infect i guess food serv fresh',
 'love ambienc .. roast chicken soup highlight dinner .. basket biryani full flavour yumm.lasagn great.nic go whole family.appetis quantiti less though',
 'i like food ambienc problem staff .. respons .. ’ order one item got someth els .. otherwis place food good ..',
 'it ’ worst servic experi food ok they took 45min get veg pulav never seen restaur take time won ’ visit',
 'waiter good enough get item order overal bad experi wait time expect ...',
 'awesom food good ambienc central locat ampl park .... coordin serv boy servic scope improv boy courteou though not sure bar close saturday even .... overal good experi & extrem valu money .... visit !',
 'wa offic lunch outing rate would mix food fine servic bad book tabl day still wait 30-40 min get one manag polit gave rubbish reason bad servic ambianc fine',
 'i realli enjoy follow .... the entranc music light seat arrang decor everyth awsom the food best servic enhanc flavour restaur i reali recommend restaur ...',
 'i came first time restaur the entranc music light seat arrang decor everyth awsom the food best servic enhanc flavour restaur',
 'pathet horribl experi ambienc hospit 1 food 1 chair tabl broken food cold tasteless buffet arrang good could bit spaciou',
 'ahm serv us polit cooper staff .. amaz food ambienc .. veg gilaffi kabab lasgna must tri .. love overal experi ....',
 'paradis biryani realli good servic also good staff friendli ambianc nice i chicken biryani mutton biryani good thank',
 'chiken biryani good spcal chiken cari good testi food and so enjoy food next time visit famili friend',
 'veri good hospit good ambianc good food v good facil pack biriyani long distanc good place visit mainli hyderabad biriyani',
 'good food tasti better music food better quick respons ... everyth good and good environ',
 'goodtast ... ever .... paradis make magic.chef gladli prepar way u prefer they nice serv everyon ... world best biryani',
 'food qualiti good .. some.tak time food arrives.but food tast good .. staff good .. perfect famili lunch dinner ... enjoy',
 'tasti food good servic enjoy lot paradis quick respons provid fast deliveri tasti food good place good econom peopl',
 'order one chicken one mutton biryani good paradis definitli great restaur biryani restaur ambin good along quick servic',
 'alway best time favorit food biryani ka baap everi time i visit i feel someth special i almost visit 20 time simpli best',
 'good tast love visit ...... with famili friend ... hope enjoy tast biryani .... and make happen everi time',
 'as usual food alway good - world famou biryani i love eat paradis biryani ever servic n ambianc also good',
 "we order tandoori chicken starter 's tasti light butter naan mutton masala main cours order chicken biryani egg mutton biryani tasti light mutton piec cook perfect",
 'veri fri approach servic especi shri krishan veri excel servic render dish tasti like visit recommend friend',

In [106]:
emoji_pattern = re.compile("["
        u"\U0001F600-\U0001F64F"
        u"\U0001F300-\U0001F5FF"
        u"\U0001F680-\U0001F6FF"
        u"\U0001F1E0-\U0001F1FF"
        u"\U00002500-\U00002BEF" 
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642" 
        u"\u2600-\u2B55"
        u"\u200d"
        u"\u23cf"
        u"\u23e9"
        u"\u231a"
        u"\ufe0f"
        u"\u3030"
                      "]+", re.UNICODE)

regexPuct = r"[\s\w\d]"

In [107]:
for index, word_list in enumerate(reviewList):
    reviewList[index] = re.sub(emoji_pattern, r'', word_list)
    reviewList[index] = ''.join(re.findall(regexPuct, reviewList[index], re.MULTILINE))
    reviewList[index] = ' '.join(reviewList[index].split())

In [108]:
df['Review'] = reviewList
df.head()

                                              Review  Rating
0  the ambienc good food quit good saturday lunch...    True
1  ambienc good pleasant even servic prompt food ...    True
2  a must tri great food great ambienc thnx servi...    True
3  soumen da arun great guy onli behavior sincere...    True
4  food goodw order kodi drumstick basket mutton ...    True

### Разделение данных

In [109]:
X = df['Review']
y = df['Rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21, stratify=y)

In [110]:
X_train.iloc[0]

'had chicken veg biryani full can vouch gor chicken good veri spici yummi love food ambienc servic polit staff clean place would recommend one visit atleast'

In [111]:
y_train.iloc[0]

np.True_

In [112]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC

In [113]:
pipe = Pipeline([
    ('vectorizer', TfidfVectorizer(ngram_range=(1, 2))), 
    ('classifire', SVC())
    ])
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

0.9075

### Тестирование модели

In [114]:
positive_sentence = "I absolutely love this product! It has exceeded all my expectations. It's well-designed, durable, and incredibly useful. I can't imagine my life without it now. I would highly recommend it to anyone looking for a high-quality, reliable product"
negative_sentence = "I bought this product, and it was a complete waste of money. It stopped working after just a week, and the customer service was unhelpful and rude. I will never purchase anything from this company again."
sentence = "I purchased this product, and it has been nothing but a disappointment. The quality is abysmal, and it didn't even last a week before falling apart. It's clear that the manufacturer prioritized cutting costs over producing a reliable item. I would strongly advise against buying this product – it's a complete waste of money."
sentence_2 = "I hate this product"

In [115]:
pipe.predict([positive_sentence, negative_sentence, sentence, sentence_2])

array([ True, False,  True,  True])

In [116]:
def preprocess(text):
    text = word_tokenize(text)
    text = " ".join([ps.stem(str(word)) for word in text if not word in stopwords.words("english") and word not in [".", ",", "?", "@", "$", "/"] and not word.isspace()])
    text = re.sub(emoji_pattern, r'', text)
    text = "".join(re.findall(regexPuct, text, re.MULTILINE))
    text = " ".join(text.split())

    return text

In [117]:
positive_sentence = preprocess(positive_sentence)
negative_sentence = preprocess(negative_sentence)
sentence = preprocess(sentence)
sentence_2 = preprocess(sentence_2)

In [118]:
pipe.predict([positive_sentence, negative_sentence, sentence, sentence_2])

array([ True, False, False,  True])